/**
 * Shared plumbing for the tools: report paths, JSON writing, number
 * formatting, and the little table printer every human summary uses.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));

/** Everything generated by these tools lands under `artifacts/`. */
export function artifactPath(...parts) {
  return resolve(REPO_ROOT, 'artifacts', ...parts);
}

export function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
  return path;
}

export function writeText(path, text) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text.endsWith('\n') ? text : `${text}\n`, 'utf8');
  return path;
}

/** Repo-relative path, for log lines that should be short and clickable. */
export function relative(path) {
  return path.startsWith(REPO_ROOT) ? path.slice(REPO_ROOT.length + 1) : path;
}

export function round(value, digits = 3) {
  if (!Number.isFinite(value)) return null;
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

/** Percentile of an already-sorted ascending array. */
export function percentile(sorted, fraction) {
  if (sorted.length === 0) return NaN;
  const index = Math.min(sorted.length - 1, Math.max(0, Math.ceil(fraction * sorted.length) - 1));
  return sorted[index];
}

export function summarise(samples) {
  const sorted = Float64Array.from(samples).sort();
  let total = 0;
  for (const value of sorted) total += value;
  return {
    count: sorted.length,
    mean: total / sorted.length,
    min: sorted[0],
    p50: percentile(sorted, 0.5),
    p95: percentile(sorted, 0.95),
    p99: percentile(sorted, 0.99),
    max: sorted[sorted.length - 1],
  };
}

/** Fixed-width table for terminal summaries. Left-aligns text, right-aligns numbers. */
export function table(headers, rows) {
  const all = [headers, ...rows].map((row) => row.map((cell) => String(cell)));
  const widths = headers.map((_, column) => Math.max(...all.map((row) => (row[column] ?? '').length)));
  const numeric = headers.map((_, column) =>
    rows.every((row) => row[column] === undefined || /^[-+]?[\d.,]+\s*\S{0,3}$/.test(String(row[column]))),
  );
  const line = (row) =>
    row
      .map((cell, column) => (numeric[column] ? String(cell).padStart(widths[column]) : String(cell).padEnd(widths[column])))
      .join('  ')
      .trimEnd();
  return [line(all[0]), widths.map((width) => '-'.repeat(width)).join('  '), ...all.slice(1).map(line)].join('\n');
}

/** `PASS`/`FAIL` with the measurement and the threshold, for one-line verdicts. */
export function verdict(ok) {
  return ok ? 'PASS' : 'FAIL';
}

export function wrap(text, width = 78, indent = '  ') {
  const words = text.split(/\s+/);
  const lines = [];
  let current = '';
  for (const word of words) {
    if (current.length + word.length + 1 > width - indent.length && current.length > 0) {
      lines.push(indent + current);
      current = word;
    } else {
      current = current.length === 0 ? word : `${current} ${word}`;
    }
  }
  if (current.length > 0) lines.push(indent + current);
  return lines.join('\n');
}
