/**
 * Foxglove Fells — wet moorland, no trees, and fog that arrives like a decision.
 *
 * The environment where visibility is the systemic personality. Peat burns
 * badly and smells extraordinary; the fog can close the walkable world down to
 * six metres and then open it again; and the only shelter is a drystone
 * sheepfold that has been there for two hundred years.
 */
export const FOXGLOVE_FELLS = {
    id: 'foxglove_fells',
    name: 'Foxglove Fells',
    tagline: 'A sheepfold on open moor, a beck you can hear but not see, and fog that comes and goes like it has somewhere to be.',
    inspiration: 'Upland moorland in a wet northern country — heather and bracken, peat hags, a drystone fold, and a track that was a packhorse route before it was anything else.',
    biomeTags: ['upland-moor', 'peat', 'oceanic-temperate', 'treeless'],
    character: {
        temperature: 'cool',
        moisture: 'wet',
        altitude: 'upland',
        treeCover: 'none',
        water: 'creek',
        eeriness: 4,
    },
    arrival: {
        approach: 'A green track through heather, sunk half a metre below the moor by centuries of feet. It holds water. There are stone flags laid in the worst bits, some of them worn hollow.',
        firstHeard: 'Water in a gill somewhere to your left, and a curlew — a long rising bubbling call that is the single most evocative sound in the catalogue and that nobody can place.',
        firstSeen: 'The fold: a low circle of drystone wall coming out of the fog about fifteen metres before you would otherwise have walked into it.',
        underfoot: 'Sodden peat that gives and squelches, then dry cropped turf inside the wall, then flagstone.',
        arrivalBeat: 'You come through the gap in the wall and the wind stops. The fire is in the old hearth against the north side, the fog is going past the top of the wall in a stream, and inside it is completely still.',
        walkSeconds: { min: 32, max: 50 },
    },
    scene: {
        ground: 'peat-moss',
        groundNote: 'Black peat under sphagnum and cotton grass, cut into hags and channels. Inside the fold it is cropped turf over flagstone, dry and springy, which makes the boundary of the shelter something you feel through your feet.',
        vegetation: [
            { kitId: 'kit_heather', label: 'Heather', density: 120, heightRange: { min: 0.2, max: 0.5 }, lowTierDrop: true, note: 'Wall to wall in every direction. Purple-black at night with firelight only ever reaching the nearest two metres of it.' },
            { kitId: 'kit_bracken_moor', label: 'Bracken', density: 30, heightRange: { min: 0.4, max: 1.2 }, lowTierDrop: true, note: 'In the sheltered channels. Dies back to rust and stays standing.' },
            { kitId: 'kit_cotton_grass', label: 'Cotton grass', density: 45, heightRange: { min: 0.2, max: 0.4 }, lowTierDrop: false, note: 'White seed heads that catch every scrap of light and are the only pale thing on the moor. They are the environment’s signature and are protected from the low-tier cut.' },
            { kitId: 'kit_foxglove', label: 'Foxglove', density: 3, heightRange: { min: 0.6, max: 1.4 }, lowTierDrop: true, note: 'Along the wall base and in the lee of the hags. Spires that stand well above everything else.' },
        ],
        landmarks: [
            { id: 'the_fold', label: 'The sheepfold', kind: 'built', handcrafted: true, note: 'A drystone circle nine metres across with one gap, a stone-lined hearth against the north wall, and a lintel over the gap with a date cut into it that is worn almost smooth.' },
            { id: 'the_beck', label: 'The beck', kind: 'water', handcrafted: true, note: 'Peat-brown water in a gill twenty metres downhill. You hear it constantly and can only see it from the edge.' },
            { id: 'the_cairn', label: 'The waymark cairn', kind: 'built', handcrafted: true, note: 'On the rise above the fold, taller than a person, built to be seen in fog. It works.' },
            { id: 'peat_cutting', label: 'The old peat cutting', kind: 'abandoned', handcrafted: true, note: 'A rectangular bench cut out of the hillside with the tool marks still in the face, and a stack of cut turves that never dried, from a year nobody names.' },
            { id: 'the_gate', label: 'The gate to nowhere', kind: 'built', handcrafted: false, note: 'An iron gate in a stretch of collapsed wall, still hung, still swinging, with moor on both sides.' },
        ],
        elevation: 'rolling',
        elevationNote: 'Long slow swells with peat hags cut into them. You are on a shoulder: the ground falls away toward the beck on one side and rises to the cairn on the other.',
        water: {
            kind: 'creek',
            label: 'The beck',
            widthM: 1.8,
            flow: 'running',
            clarity: 0.4,
            fishable: true,
            skippable: false,
            note: 'Peat-stained the colour of strong tea, running fast over gritstone in a series of small falls. Small wild trout, none of them longer than your hand.',
        },
        drawDistanceM: 55,
        fog: { colour: '#2f3336', density: 0.04, note: 'The most variable fog in the catalogue: on a clear night it is barely present and on a bad one it closes to six metres and the fold becomes the entire world.' },
        nightPalette: {
            zenith: '#080b12',
            horizon: '#242a2c',
            ground: '#241f1c',
            foliage: '#2a2430',
            rock: '#4d4c47',
            water: '#2b211a',
            fireGlow: '#ff9748',
            moonlight: '#a5b2bd',
            shadow: '#070808',
        },
        skyOpenness: 0.75,
        walkableRadiusM: 40,
    },
    weather: {
        id: 'foxglove-fells',
        weights: { fog: 6, overcast: 5, 'light-rain': 5, rain: 3, wind: 4, 'high-cloud': 3, clear: 2, storm: 1 },
        baseTempC: 8,
        baseWind: 3.2,
        exposure: 0.5,
        skyEventChance: 0.14,
        skyEvents: ['moonbow', 'aurora', 'meteor-shower'],
        transitionSeconds: 120,
    },
    weatherCharacter: {
        temperatureNote: 'Cold in a way that is entirely about being wet. Nothing here is ever quite dry, including you, and the fire matters more than at any other site.',
        windNote: 'Constant over the wall and completely absent inside it. The wall is doing a job it has been doing for two hundred years and you can feel exactly where it stops working.',
        exposureNote: 'The fastest-changing weather in the catalogue — transitions every two minutes on average. Fog can arrive and leave inside a single roasting session.',
        nightRangeC: { min: 2, max: 12 },
    },
    fuel: {
        sources: [
            { woodId: 'birch', weight: 5, foundAs: 'A bag of cut birch by the hearth, left by whoever was here last, kept dry under a slate.', moistureBias: 0.05 },
            { woodId: 'aspen', weight: 3, foundAs: 'Willow scrub from the gill, green and difficult.', moistureBias: 0.28 },
            { woodId: 'oak', weight: 2, foundAs: 'Bog oak — black, dense, thousands of years old, dug out of a peat hag.', moistureBias: 0.2 },
        ],
        note: 'The dried peat turves burn like nothing else in the product: they barely flame, they glow deep red all the way through, and the smoke is sweet and low and smells like the whole history of the place. Bog oak on a peat bed makes an ember pit that will outlast the night, and it takes real patience to get there.',
    },
    wildlife: [
        {
            id: 'curlew',
            label: 'Curlew',
            shyness: 0.85,
            curiosity: 0.1,
            window: ['dusk', 'pre-dawn', 'dawn'],
            attractedBy: ['quiet'],
            repelledBy: ['footsteps', 'voices', 'flashlight'],
            canPersist: true,
            investigatesObjects: false,
            traces: ['long curved bill probe marks in soft peat'],
            note: 'Never seen. The call comes out of the fog from a different direction each time and is the single sound most likely to make a player stop what they are doing.',
        },
        {
            id: 'hill_sheep',
            label: 'Hill sheep',
            shyness: 0.35,
            curiosity: 0.55,
            window: ['dusk', 'early-night', 'dawn'],
            attractedBy: ['shelter', 'warmth', 'quiet'],
            repelledBy: ['sudden-movement', 'radio-music'],
            canPersist: true,
            investigatesObjects: true,
            traces: ['wool caught on the wall stones', 'droppings inside the fold', 'a bag of kindling knocked over and ignored'],
            note: 'Three of them, unshepherded, with a horn mark sprayed on the fleece. They come and stand in the lee of the wall in bad weather, look at you at length, and stay. It is impossible to feel alone with a sheep looking at you.',
        },
        {
            id: 'short_eared_owl',
            label: 'Short-eared owl',
            shyness: 0.7,
            curiosity: 0.4,
            window: ['dusk', 'pre-dawn'],
            attractedBy: ['quiet', 'stillness', 'moonlight'],
            repelledBy: ['flashlight', 'voices'],
            canPersist: true,
            investigatesObjects: false,
            traces: ['a pellet on the cairn', 'a single primary feather in the heather'],
            note: 'Quarters the moor at waist height in complete silence, pale underneath, and passes through the firelight without a sound. Hunts in daylight and dusk, which is why you actually see this one.',
        },
        {
            id: 'moor_frog',
            label: 'Frogs in the flushes',
            shyness: 0.5,
            curiosity: 0.1,
            window: ['early-night', 'deep-night'],
            attractedBy: ['rain', 'water-edge'],
            repelledBy: ['cold-air'],
            canPersist: false,
            investigatesObjects: false,
            traces: ['spawn in a boot print full of water'],
            note: 'A soft purring chorus from the wet flushes after rain that stops the instant you get within five metres.',
        },
    ],
    ambience: {
        wind: { character: 'gusting', baseLevel: 0.55, gustiness: 0.8, material: 'heather, cotton grass and the top course of a drystone wall' },
        insectDensity: 0.3,
        insectNote: 'Midges in still damp air, which is often, and nothing else. They are audible as a fine high shimmer near the ears and they hate smoke, which is a real and usable mechanic.',
        waterPresence: 0.45,
        reverb: 'openForest',
        reverbNote: 'Outside the wall, nothing at all — open moor absorbs everything. Inside the fold there is a tight little stone slap-back, and crossing the gap in the wall audibly changes the room. It is the only environment where you can hear yourself enter shelter.',
        distantEvents: [
            { id: 'curlew_far', label: 'A curlew, further out', weight: 6, minGapSeconds: 110, note: 'The rising bubble, from somewhere in the fog, answered once from much further away.' },
            { id: 'stone_falls', label: 'A stone comes off the wall', weight: 3, minGapSeconds: 400, note: 'One clack and a small settle from a stretch of wall you cannot see. Two hundred years of this.' },
            { id: 'sheep_cough', label: 'A sheep coughs', weight: 4, minGapSeconds: 200, note: 'An astonishingly human sound from ten metres away in the fog, and the funniest thing in the catalogue the first time it happens.' },
            { id: 'gate_swing', label: 'The gate swings', weight: 4, minGapSeconds: 240, note: 'A rusted hinge, twice, and then stopping. The wind did it. The wind does it.' },
            { id: 'beck_surge', label: 'The beck rises a note', weight: 5, minGapSeconds: 150, note: 'After rain upstream, twenty minutes before the rain reaches you.' },
        ],
        nightFloorDb: -44,
    },
    activities: [
        { id: 'fire-tending', label: 'Tend the fire', prominence: 'signature', note: 'Wet fuel, peat turves, and a stone hearth that has been used for this for centuries. The hardest fire to start and the best one to have got going.' },
        { id: 'fishing', label: 'Fish the beck', prominence: 'available', note: 'Tiny wild trout in pockets the size of a bath. Entirely about the crouching and the looking.' },
        { id: 'wind-listening', label: 'Listen at the wall', prominence: 'signature', note: 'Different courses of the drystone wall make different notes in different winds. Move along it and the pitch changes. People will find one gap that whistles and come back to it.' },
        { id: 'photography', label: 'Photograph', prominence: 'notable', note: 'Fog, firelight and a stone wall. The frost on the sandwich against wet gritstone is the shot; the fog does the vignetting for you.' },
        { id: 'radio', label: 'Radio', prominence: 'notable', note: 'Long wave gets in where nothing else does, and there is one station that is only ever there when the fog is.' },
        { id: 'flashlight', label: 'Flashlight', prominence: 'notable', note: 'In fog the beam is a solid cone that ends. Sweeping it around the inside of the fold is a genuinely lovely thing to do.' },
        { id: 'wildlife-watching', label: 'Watch for wildlife', prominence: 'available', note: 'The owl comes through at dusk and is gone in two seconds. The sheep are simply there.' },
        { id: 'foraging', label: 'Cut and dry peat', prominence: 'notable', note: 'From the old cutting, with the tool that is leaning in it. It will not be dry tonight. It will be dry next time.' },
        { id: 'cairn-reading', label: 'Walk up to the cairn', prominence: 'available', note: 'Above the fog line, sometimes, with the moor cloud below you and the fire’s glow showing through it.' },
    ],
    radio: {
        stations: [
            { id: 'lw_198', dial: 198, band: 'am', name: 'Long wave, national', character: 'community', reception: 0.86, note: 'Shipping forecast at the top of the hour: sea areas, wind, sea state, visibility, read in a level voice. The best radio in the entire product and it is not close.' },
            { id: 'kfel_1027', dial: 102.7, band: 'fm', name: 'Dales FM overnight', character: 'lofi', reception: 0.44, note: 'Automated overnight from a transmitter on the next fell. Fades entirely when the cloud comes down, which it does.' },
            { id: 'moor_repeater', dial: 145.6, band: 'fm', name: 'Hill repeater', character: 'environmental', reception: 0.58, note: 'A courtesy beep and long silences. Two people who cannot see each other, checking they still can.' },
            { id: 'fog_station', dial: 1278, band: 'am', name: 'The station that is only there in fog', character: 'strange', reception: 0.3, note: 'A dance band recording with a lot of surface noise, and once, faintly, someone in the room where it is playing moving a chair. Gone the moment the fog lifts. This is a propagation effect. It is also not.' },
        ],
        baseReception: 0.52,
        receptionNote: 'Terrain-shadowed on three sides and wide open to the north. Long wave is immune to all of it and is the reason the shipping forecast is the sound of this place.',
        betweenStations: 'Wet, heavy static with a low rumble under it, and the whole band lifting and dropping as the cloud moves.',
    },
    secrets: [
        {
            id: 'ff_lintel_date',
            title: 'The date on the lintel',
            discovery: 'Rub the moss off the stone over the gap in the wall.',
            telling: 'A date, four figures, and two sets of initials — and below them, cut much more recently and much more shallowly, the same two sets of initials again.',
            channels: ['notes'],
            oneTime: false,
            leavesEvidence: null,
            rarity: 0.45,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'ff_turves_that_never_dried',
            title: 'The stack that never dried',
            discovery: 'The turves at the old peat cutting, stacked in a herringbone to dry, and never collected.',
            telling: 'Underneath the stack, wrapped in oilcloth, is a peat spade with a name burned into the handle. It is still sharp. Somebody stopped, mid-job, and never came back for their tool — and the tool is the only thing here in good condition.',
            channels: ['strange-objects'],
            oneTime: true,
            leavesEvidence: 'The spade stands upright in the cutting face on every later visit and the oilcloth stays folded on the stack.',
            rarity: 0.25,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'ff_the_fog_takes_the_cairn',
            title: 'When the cairn is not there',
            discovery: 'You walk up to the rise in thick fog and the waymark cairn is not on it.',
            telling: 'Ten metres further on, it is. You misjudged the distance in fog, which is exactly what fog does and exactly what the cairn is for. It is the most reassuring frightening thing in the game.',
            channels: ['campsite-changes'],
            oneTime: false,
            leavesEvidence: null,
            rarity: 0.3,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'ff_the_dance_band',
            title: 'The chair in the recording',
            discovery: 'Stay on the fog station long enough, with the volume up, on a night when the cloud is fully down.',
            telling: 'Between two numbers, in the surface noise, someone in the room where the record is playing scrapes a chair back and says four words. They are not clear. They are unmistakably warm.',
            channels: ['radio'],
            oneTime: true,
            leavesEvidence: 'The station is afterwards listed in the Passport with the dial position written in by hand, and the entry has a small pressed sprig of heather in it.',
            rarity: 0.14,
            optional: true,
            gatesNothing: true,
        },
    ],
    machine: {
        quirkWeights: { 'sticky-door': 3.5, 'rough-fan': 2.5, 'warm-latch': 2, 'slow-amber': 2 },
        flavourNote: 'The unit stands on four slate pads inside the fold, out of the wind, and it is the only thing at this site that has been kept properly dry. The door gasket has taken on so much damp over the years that the first close never seats and everyone who camps here learns to give it the second push without thinking about it.',
        stickerHint: 'SERVICE — DO NOT PAINT, and it has, unmistakably, been painted.',
        frostNote: 'In this humidity the frost is thick, fast and beautiful — the heaviest frost pattern the machine ever produces, and it holds for minutes.',
    },
    procedural: {
        seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'fog', 'peat', 'machine'],
        variations: [
            { id: 'cloud_base', label: 'Cloud base height', range: { min: 0, max: 60 }, unit: 'metres above the fold', note: 'At zero the whole environment is inside cloud and the walkable world is the fold. This is the defining variation of the site.' },
            { id: 'beck_flow', label: 'Beck flow', range: { min: 0.3, max: 1.6 }, unit: 'multiplier', note: 'Governs how loud the water is, whether the small falls are audible, and whether the crossing stones are covered.' },
            { id: 'sheep_present', label: 'Sheep in the fold', range: { min: 0, max: 3 }, unit: 'animals', note: 'They come in when the weather is bad, which is to say usually.' },
            { id: 'dry_fuel_bag', label: 'Kindling left by the last person', range: { min: 2, max: 10 }, unit: 'pieces', note: 'Never zero. Somebody always leaves some. Whether you leave some is up to you and the world notices.' },
            { id: 'foxglove_count', label: 'Foxglove spires', range: { min: 0, max: 14 }, unit: 'plants', note: 'Seasonal-feeling. In their absence the wall base is much darker.' },
        ],
        invariants: [
            'The fold, its single gap, and the stone hearth on the north side.',
            'The lintel and its date.',
            'The waymark cairn on the rise.',
            'The gate hanging in the collapsed wall.',
        ],
    },
    discovery: {
        weight: 9,
        affinities: { 'maritime-east': 2.4, 'maritime-west': 1.6, boreal: 1.2, highland: 1.4, unknown: 1.1, 'continental-interior': 0.8, mediterranean: 0.9, 'arid-interior': 0.5, 'humid-subtropical': 0.6 },
        note: 'The oceanic-temperate corner. Weighted toward wet northern regions, reachable everywhere; its fire lesson is the hardest and most satisfying in the set.',
    },
    performance: {
        cost: 'moderate',
        midTierDrawCalls: 68,
        midTierTriangles: 36000,
        dynamicLights: 3,
        lowTierCuts: [
            'Heather scatter 120 → 35 per 100m², with the loss hidden by fog rather than by a texture swap.',
            'Drystone wall drops from per-stone geometry to a two-LOD strip with a normal map; only the twelve stones nearest the fire keep real silhouettes.',
            'Bracken and foxglove drop to 25%. Cotton grass is protected — it is the only bright thing in the environment.',
            'Fog stays at full quality at every tier; it is doing the hiding that makes all the other cuts invisible.',
        ],
        note: 'The wall is the expensive object and also the whole environment, so it gets a careful LOD chain rather than a cut. Short draw distance and heavy fog make this one of the easier heavy-scatter sites to hit budget on.',
    },
};
//# sourceMappingURL=foxglove-fells.js.map