import type { EnvironmentManifest } from '../schema.js';

/**
 * Lantern Mesa — hot rock, no trees, and more sky than anywhere else.
 *
 * The stargazing environment. Also the best fire in the catalogue: mesquite
 * makes a deep, long-lived ember bed, and with no canopy and no damp the
 * ember-versus-flame lesson (spec deviation D4) is at its most legible here.
 */
export const LANTERN_MESA: EnvironmentManifest = {
  id: 'lantern_mesa',
  name: 'Lantern Mesa',
  tagline: 'Slickrock still giving back the day’s heat, and a sky with no floor to it.',
  inspiration:
    'A dispersed camping bench on a red sandstone plateau in the desert southwest — a dry wash below, a butte on the horizon, and a fire ring built by whoever was here last.',
  biomeTags: ['high-desert', 'slickrock', 'dispersed-camping', 'dark-sky'],
  character: {
    temperature: 'hot',
    moisture: 'arid',
    altitude: 'upland',
    treeCover: 'none',
    water: 'none',
    eeriness: 2,
  },
  arrival: {
    approach:
      'A two-track that stops being a road somewhere behind you. You walk the last stretch on bare sandstone, following cairns, and the rock is still warm through your shoes at midnight.',
    firstHeard:
      'Nothing. Genuinely nothing, for long enough that you check whether the audio is working — and then a single cricket, very far away, alone.',
    firstSeen:
      'The Milky Way, before you see the ground. You look up first here, every time.',
    underfoot:
      'Sandstone, gritty, absolutely solid. Then a patch of red dust that puffs and hangs.',
    arrivalBeat:
      'The bench opens out and the fire ring is a ring of blackened rocks on bare stone, low and orange, with the SM-01 casting one long hard shadow across forty feet of rock.',
    walkSeconds: { min: 26, max: 42 },
  },
  scene: {
    ground: 'red-dust',
    groundNote:
      'Cross-bedded sandstone with drifts of red dust in the hollows, and one pothole that holds a dish of rainwater for a week after it rains.',
    vegetation: [
      { kitId: 'kit_blackbrush', label: 'Blackbrush', density: 9, heightRange: { min: 0.3, max: 0.7 }, lowTierDrop: true, note: 'Tight grey-black scribbles. Reads as texture on the rock, not as plants.' },
      { kitId: 'kit_juniper_snag', label: 'Dead juniper', density: 1.2, heightRange: { min: 1.5, max: 3 }, lowTierDrop: false, note: 'Silver, twisted, sculptural. Each one is a landmark on its own.' },
      { kitId: 'kit_cryptobiotic', label: 'Cryptobiotic crust', density: 30, heightRange: { min: 0.02, max: 0.08 }, lowTierDrop: true, note: 'Black knobbled soil crust in the sand pockets. Footprints in it persist across visits and never fade.' },
    ],
    landmarks: [
      { id: 'the_butte', label: 'The far butte', kind: 'natural', handcrafted: true, note: 'A flat-topped silhouette on the horizon that eats a bite out of the star field. It is the compass for the whole site.' },
      { id: 'cairn_line', label: 'The cairn line', kind: 'built', handcrafted: true, note: 'Seven stacked-rock cairns leading in from the two-track. One has fallen over and been rebuilt slightly wrong.' },
      { id: 'pothole', label: 'The pothole', kind: 'water', handcrafted: true, note: 'A basin in the rock, a metre across. Full, half full, or dry, depending. Reflects the whole sky when full.' },
      { id: 'ring_of_rocks', label: 'The fire ring someone built', kind: 'camp', handcrafted: true, note: 'Blackened sandstone slabs, one cracked clean through by heat. Nobody knows who made it.' },
      { id: 'dry_wash', label: 'The dry wash', kind: 'natural', handcrafted: false, note: 'Ten metres below the bench, floored in pale sand and polished cobble. Walkable, and colder than the rock above it.' },
    ],
    elevation: 'bench',
    elevationNote:
      'A flat shelf with a drop on one side and a slow rise on the other. The drop is the reason the sky feels bottomless.',
    drawDistanceM: 260,
    fog: { colour: '#171017', density: 0.0035, note: 'Almost none. The longest sightlines in the catalogue, which is the whole point of this place.' },
    nightPalette: {
      zenith: '#05060f',
      horizon: '#1a1017',
      ground: '#40261d',
      foliage: '#241f18',
      rock: '#57342a',
      water: null,
      fireGlow: '#ff8c3a',
      moonlight: '#b6b0c8',
      shadow: '#0a0508',
    },
    skyOpenness: 0.98,
    walkableRadiusM: 60,
  },
  weather: {
    id: 'lantern-mesa',
    weights: { clear: 9, 'high-cloud': 3, wind: 2, overcast: 1 },
    baseTempC: 22,
    baseWind: 1.6,
    exposure: 0.7,
    skyEventChance: 0.3,
    skyEvents: ['meteor-shower', 'heat-lightning'],
    transitionSeconds: 320,
  },
  weatherCharacter: {
    temperatureNote:
      'Hot rock, cold air. You sit on stone that is still radiating the afternoon while your breath is cool. The temperature drop after midnight is genuinely fast.',
    windNote: 'Comes up off the wash in long even pushes, then stops completely for minutes at a time.',
    exposureNote: 'Open, but the rock ring is a real windbreak at ember height. Flames get pushed around; embers barely notice.',
    nightRangeC: { min: 11, max: 29 },
  },
  fuel: {
    sources: [
      { woodId: 'mesquite', weight: 7, foundAs: 'A neat stack behind the fire ring, left by whoever built it, bone dry.', moistureBias: -0.08 },
      { woodId: 'oak', weight: 3, foundAs: 'Scrub oak from the head of the wash, hard as bone and half the size you want.', moistureBias: -0.06 },
      { woodId: 'pine', weight: 1, foundAs: 'A single pinyon limb, resinous, that will flare and be gone.', moistureBias: -0.05 },
    ],
    note:
      'Mesquite is slow to take and then simply refuses to stop. Get it lit early and by the time you want to roast there is a bed of coals the colour of a streetlight that will still be usable an hour later. This is the site that teaches patience.',
  },
  wildlife: [
    {
      id: 'kangaroo_rat',
      label: 'Kangaroo rat',
      shyness: 0.7,
      curiosity: 0.65,
      window: ['early-night', 'deep-night'],
      attractedBy: ['crumbs', 'stillness', 'moonlight'],
      repelledBy: ['flashlight', 'footsteps'],
      canPersist: false,
      investigatesObjects: true,
      traces: ['a fan of tail-drag and two-foot prints in the dust', 'a small excavation next to the bear-proof bag'],
      note: 'Moves in perfectly flat arcs, like something bouncing. Impossible to photograph and everyone tries.',
    },
    {
      id: 'poorwill',
      label: 'Common poorwill',
      shyness: 0.85,
      curiosity: 0.4,
      window: ['dusk', 'early-night', 'pre-dawn'],
      attractedBy: ['quiet', 'warmth', 'firelight'],
      repelledBy: ['voices', 'compressor-noise'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a warm hollow in the dust where it sat all evening'],
      note: 'Sits on the warm rock at the edge of the firelight and calls its own name, twice, then waits an unreasonable amount of time and does it again. Eyes reflect orange.',
    },
    {
      id: 'ringtail',
      label: 'Ringtail',
      shyness: 0.75,
      curiosity: 0.95,
      window: ['deep-night'],
      attractedBy: ['food-smell', 'marshmallow-smell', 'quiet', 'crumbs'],
      repelledBy: ['sudden-movement', 'camera-flash', 'radio-music'],
      canPersist: true,
      investigatesObjects: true,
      traces: ['a chocolate wrapper up on a rock ledge', 'small hand-shaped prints on the SM-01 lid'],
      note: 'Enormous eyes, banded tail, hands. Will absolutely go through your things while looking directly at you and is the single most charming animal in the game.',
    },
    {
      id: 'bark_scorpion_glow',
      label: 'Scorpions under UV',
      shyness: 0.2,
      curiosity: 0.05,
      window: ['deep-night'],
      attractedBy: ['warmth'],
      repelledBy: ['sudden-movement'],
      canPersist: false,
      investigatesObjects: false,
      traces: ['none — they leave nothing at all'],
      note: 'Only visible if the player switches the flashlight to its UV setting, at which point six of them light up cyan across the rock. Harmless, uninterested, and startlingly beautiful. They do not approach the camp.',
    },
  ],
  ambience: {
    wind: { character: 'steady', baseLevel: 0.28, gustiness: 0.45, material: 'blackbrush and the lip of the dry wash' },
    insectDensity: 0.22,
    insectNote: 'Sparse and enormous-sounding. One cricket at forty metres, then a second answering from two hundred. Long true silences between.',
    waterPresence: 0.02,
    reverb: 'canyon',
    reverbNote: 'A hard slap off the rock at close range and a long thin return off the far wall of the wash roughly two seconds later. Sit and clap once; everyone does.',
    distantEvents: [
      { id: 'rockfall', label: 'A rock lets go somewhere in the wash', weight: 3, minGapSeconds: 400, note: 'One knock, then a small cascade, then silence resuming.' },
      { id: 'coyote_chorus', label: 'Coyotes, several ridges over', weight: 4, minGapSeconds: 300, note: 'Starts as one, becomes six, stops mid-note. Never closer than very far.' },
      { id: 'plane_high', label: 'A very high aircraft', weight: 3, minGapSeconds: 360, note: 'A tiny moving light and a sound that arrives long after it has passed.' },
      { id: 'thermal_tick', label: 'The rock ticking as it cools', weight: 5, minGapSeconds: 45, note: 'Sharp, small, from directly underneath. The mesa letting go of the day.' },
    ],
    nightFloorDb: -64,
  },
  activities: [
    { id: 'fire-tending', label: 'Tend the fire', prominence: 'signature', note: 'The best ember bed available. Rake it wide and flat and the roasting window opens up enormously.' },
    { id: 'stargazing', label: 'Stargaze', prominence: 'signature', note: 'The reference implementation. Naked-eye Milky Way structure, zodiacal light before dawn, satellites, and meteors often enough to be worth lying down for.' },
    { id: 'telescope', label: 'Telescope', prominence: 'notable', note: 'A small refractor on the flat rock. Saturn is a genuine gasp at PS1 resolution.' },
    { id: 'binoculars', label: 'Binoculars', prominence: 'available', note: 'Better than the telescope for the Milky Way and for finding the eyes at the edge of the firelight.' },
    { id: 'photography', label: 'Photograph', prominence: 'notable', note: 'Hard shadows and a black sky. The sandwich lit only by the machine, on red rock, is the cleanest product shot in the catalogue.' },
    { id: 'radio', label: 'Radio', prominence: 'available', note: 'Almost nothing on FM and the entire continent on AM after midnight.' },
    { id: 'flashlight', label: 'Flashlight', prominence: 'notable', note: 'It has a UV mode. Nobody tells you this.' },
    { id: 'echo-calling', label: 'Call into the wash', prominence: 'available', note: 'Two seconds out, two seconds back, slightly changed.' },
    { id: 'cairn-reading', label: 'Read the cairns', prominence: 'available', note: 'Seven of them. The sixth one is not where the others suggest it should be.' },
    { id: 'shadow-puppets', label: 'Shadow puppets', prominence: 'signature', note: 'The fire throws hard-edged shadows forty feet across bare rock. A hand becomes a two-storey animal. This is what a low-poly hard shadow was made for.' },
  ],
  radio: {
    stations: [
      { id: 'kmsa_1017', dial: 101.7, band: 'fm', name: 'KMSA — Overnight', character: 'lofi', reception: 0.35, note: 'Drifts in and out with the temperature inversion. Slow dusty instrumentals and a station ident that has not been re-recorded since the nineties.' },
      { id: 'clear_channel_1030', dial: 1030, band: 'am', name: 'A 50 kW clear channel', character: 'community', reception: 0.88, note: 'Arrives from a thousand miles away like it is next door. Overnight call-in show about nothing at all. The most companionable sound in the game.' },
      { id: 'obs_net', dial: 162.4, band: 'fm', name: 'Observatory net', character: 'environmental', reception: 0.6, note: 'Seeing conditions, humidity, a dome closing. Two people who work nights, talking the way people do at 3am.' },
      { id: 'sw_5915', dial: 5915, band: 'shortwave', name: '5915 kHz', character: 'strange', reception: 0.42, note: 'An interval signal — nine notes on something like a xylophone — repeating for eleven minutes and then stopping without ever announcing anything.' },
    ],
    baseReception: 0.5,
    receptionNote: 'Line of sight to nothing and skywave to everywhere. FM is a desert; AM after midnight is a party.',
    betweenStations: 'A dry, thin hiss with heat-lightning crackle riding on it whenever the horizon flickers.',
  },
  secrets: [
    {
      id: 'lm_sixth_cairn',
      title: 'The sixth cairn',
      discovery: 'Walk the cairn line back out at night and the sixth one leads somewhere the others do not.',
      telling: 'Forty metres off the route it points to a slab with a single word scratched into the varnish, in handwriting, upside down relative to the approach — as if written by someone lying down.',
      channels: ['strange-objects', 'notes'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.3,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'lm_pothole_sky',
      title: 'The pothole full of sky',
      discovery: 'When the pothole holds water and the air is still, it takes the entire sky in one dish.',
      telling: 'Kneel over it and there are stars underneath you. A meteor crossing while you are looking down into it is the single most-photographed moment this environment produces.',
      channels: ['campsite-changes'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.4,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'lm_survey_marker',
      title: 'The survey marker',
      discovery: 'A brass disk set into the rock at the edge of the bench, easy to walk over a hundred times.',
      telling: 'It gives an elevation and a year and the name of an agency, and on the reverse of the stamping, very faintly, someone has added a second elevation that is nine feet different.',
      channels: ['strange-objects', 'notes'],
      oneTime: true,
      leavesEvidence: 'Once found, the disk is polished clean of dust on every later visit, and stays that way.',
      rarity: 0.25,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'lm_lit_window',
      title: 'The light on the butte',
      discovery: 'Very occasionally, through binoculars, there is a single warm light near the top of the far butte.',
      telling: 'It is on for a while. Then it is not. There is no road up there and the game never mentions it again, which is exactly the right amount of mention.',
      channels: ['recurring-figures'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.08,
      optional: true,
      gatesNothing: true,
    },
  ],
  machine: {
    quirkWeights: { 'flicker-segment': 3, 'loud-compressor': 2.5, 'long-hold': 2, 'warm-latch': 2 },
    flavourNote:
      'Sun has taken the top surfaces of this unit down to a chalky near-white while the shaded side is still factory enamel. The compressor works visibly harder against the heat in the rock, and the run takes a few seconds longer than the plate says it should.',
    stickerHint: 'NIGHT USE PERMITTED, sun-bleached to a ghost of itself.',
    frostNote: 'Frost forms fast and sublimates faster in the dry air — it is gone from the door within thirty seconds, which makes the window worth watching in real time.',
  },
  procedural: {
    seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'sky', 'traces', 'machine'],
    variations: [
      { id: 'pothole_level', label: 'Water in the pothole', range: { min: 0, max: 1 }, unit: 'normalised', note: 'Dry, dish, or full mirror. Gates nothing; changes everything about how the site photographs.' },
      { id: 'dust_drift', label: 'Dust drift depth', range: { min: 0.4, max: 1.5 }, unit: 'multiplier', note: 'How much red dust has collected in the hollows, and how visibly your footprints record the night.' },
      { id: 'mesquite_stack', label: 'Mesquite remaining on the stack', range: { min: 4, max: 16 }, unit: 'pieces', note: 'Never zero.' },
      { id: 'cairn_state', label: 'Rebuilt cairn shape', range: { min: 0, max: 1 }, unit: 'variant', note: 'The fallen cairn is restacked slightly differently each visit, by nobody.' },
      { id: 'inversion_strength', label: 'Temperature inversion', range: { min: 0, max: 1 }, unit: 'normalised', note: 'Drives FM reception, how far the coyotes carry, and how sharply the rock ticks.' },
    ],
    invariants: [
      'The far butte and its bite out of the star field.',
      'Seven cairns, one of them wrong.',
      'The cracked slab in the fire ring.',
      'The brass survey marker, whether or not it has been found.',
    ],
  },
  discovery: {
    weight: 11,
    affinities: { 'arid-interior': 2.4, mediterranean: 1.5, highland: 1.2, 'continental-interior': 1.1, unknown: 1.3, boreal: 0.6, 'maritime-west': 0.8, 'maritime-east': 0.6, 'humid-subtropical': 0.7 },
    note: 'The showpiece for dark-sky play. Heavily weighted in dry regions and still very findable everywhere, because everybody deserves to see this sky.',
  },
  performance: {
    cost: 'light',
    midTierDrawCalls: 41,
    midTierTriangles: 18000,
    dynamicLights: 3,
    lowTierCuts: [
      'Cryptobiotic crust and blackbrush scatter drop to 25%.',
      'Star field goes from 1400 to 500 points with the Milky Way band baked into the skybox.',
      'Hard shadow map 1024 → 512; the shadows get chunkier, which honestly suits it.',
      'Draw distance 260m → 140m; the butte moves to a billboard.',
    ],
    note: 'Geometrically trivial. The only real cost is the 260m draw distance and the star field, and both scale cleanly. Ships well on the oldest supported devices.',
  },
};
