import type { EnvironmentManifest } from '../schema.js';

/**
 * Longlight Shore — cold ocean, warm fire, the loudest ambience in the set.
 *
 * The id contains `shore`, which is load-bearing: `packages/sim/src/sandwich.ts`
 * awards the *Driftwood* class to sandwiches made at a shore campsite by a
 * well-worn machine. Salt-laden driftwood also gives this fire coloured flame
 * and a spit that exists nowhere else in the catalogue.
 */
export const LONGLIGHT_SHORE: EnvironmentManifest = {
  id: 'longlight_shore',
  name: 'Longlight Shore',
  tagline: 'A fire in the lee of a drift log, with the tide coming in somewhere out in the dark.',
  inspiration:
    'A cold-water Pacific beach below a headland — wind-flagged spruce, a wrack line of enormous bleached logs, and a light on the point that turns once every nine seconds.',
  biomeTags: ['coastal', 'temperate-maritime', 'wrack-line', 'wind-flagged-forest'],
  character: {
    temperature: 'cool',
    moisture: 'wet',
    altitude: 'sea-level',
    treeCover: 'sparse',
    water: 'sea',
    eeriness: 3,
  },
  arrival: {
    approach:
      'A sand-drifted trail through salal, shoulder height and wet, that dumps you abruptly onto open beach. The last twenty metres you are walking on planks laid over sand, half of them missing.',
    firstHeard:
      'Surf — not crashing, just an enormous slow inhale and release that has clearly been going on all day without you.',
    firstSeen:
      'The light on the point, sweeping. It reaches you before the fire does, and for a second it is the only thing in the world.',
    underfoot:
      'Wet plank, then dry sand that squeaks, then coarse sand and shell hash that grinds.',
    arrivalBeat:
      'You come around the end of a drift log the size of a bus and the wind stops, completely, and the fire is right there in the pocket of stillness behind it.',
    walkSeconds: { min: 30, max: 46 },
  },
  scene: {
    ground: 'fine-sand',
    groundNote:
      'Grey-brown sand shading to shell hash and rounded cobble at the high tide line. Firelight makes every footprint a crater.',
    vegetation: [
      {
        kitId: 'kit_shore_spruce',
        label: 'Wind-flagged spruce',
        density: 3,
        heightRange: { min: 4, max: 12 },
        lowTierDrop: false,
        note: 'Every branch on the landward side. They lean inland like they are all listening to the same thing.',
      },
      {
        kitId: 'kit_dune_grass',
        label: 'Dune grass',
        density: 60,
        heightRange: { min: 0.3, max: 0.8 },
        lowTierDrop: true,
        note: 'Scribes perfect arcs in the sand around each clump when the wind turns.',
      },
      {
        kitId: 'kit_salal',
        label: 'Salal thicket',
        density: 18,
        heightRange: { min: 0.9, max: 1.8 },
        lowTierDrop: true,
        note: 'Waxy, black-green, holds the trail edge. Only the top leaves ever catch light.',
      },
    ],
    landmarks: [
      { id: 'the_big_log', label: 'The big log', kind: 'natural', handcrafted: true, note: 'A root-wad-and-all spruce trunk twenty metres long, silver-grey, sand piled against its seaward side. It is the windbreak, the bench, and the wall of the room.' },
      { id: 'point_light', label: 'The light on the point', kind: 'sky', handcrafted: true, note: 'A slow sweep every nine seconds, low on the horizon. It never fails and it never explains itself.' },
      { id: 'plank_walk', label: 'The broken plank walk', kind: 'built', handcrafted: false, note: 'Boards over sand, gaps where boards used to be, one with a boot heel still stuck between them.' },
      { id: 'wrack_line', label: 'The wrack line', kind: 'natural', handcrafted: false, note: 'Kelp, feathers, a fishing float, rope. Reshuffled every visit by a tide you never see move.' },
    ],
    elevation: 'flat',
    elevationNote: 'Dead flat with a low berm at the wrack line. The only relief is the log itself.',
    water: {
      kind: 'sea',
      label: 'The surf',
      widthM: 400,
      flow: 'tidal',
      clarity: 0.25,
      fishable: true,
      skippable: true,
      note: 'Never reaches the fire. The tide line advances between visits, never during one — the sea is atmosphere, not threat.',
    },
    drawDistanceM: 70,
    fog: { colour: '#232b33', density: 0.034, note: 'Salt haze. Thick enough that the point light becomes a glowing cone rather than a beam.' },
    nightPalette: {
      zenith: '#070c14',
      horizon: '#26323c',
      ground: '#3b382f',
      foliage: '#182219',
      rock: '#4a4740',
      water: '#141d26',
      fireGlow: '#ffb257',
      moonlight: '#9db6cd',
      shadow: '#05080d',
    },
    skyOpenness: 0.86,
    walkableRadiusM: 48,
  },
  weather: {
    id: 'longlight-shore',
    weights: { overcast: 5, 'high-cloud': 3, fog: 4, 'light-rain': 3, rain: 2, wind: 4, clear: 2, storm: 1 },
    baseTempC: 9,
    baseWind: 3.1,
    exposure: 0.85,
    skyEventChance: 0.09,
    skyEvents: ['meteor-shower', 'moonbow'],
    transitionSeconds: 165,
  },
  weatherCharacter: {
    temperatureNote:
      'Never warm and never quite freezing. The cold is in the damp rather than the number — you feel it on the side away from the fire.',
    windNote: 'Onshore and constant, dropping to nothing the moment you step behind the log. Learning that pocket is the first thing this site teaches.',
    exposureNote: 'The most exposed pit in the catalogue by a wide margin. Position of the windbreak matters more here than anywhere.',
    nightRangeC: { min: 5, max: 13 },
  },
  fuel: {
    sources: [
      { woodId: 'driftwood', weight: 8, foundAs: 'Anywhere along the wrack line, silver-dry on top and soaked underneath.', moistureBias: 0.05 },
      { woodId: 'pine', weight: 2, foundAs: 'A bundle someone carried down and did not use, going soft in the damp.', moistureBias: 0.12 },
      { woodId: 'oak', weight: 1, foundAs: 'A single broken pallet slat, nail holes and all.', moistureBias: -0.05 },
    ],
    note:
      'Salt in the driftwood throws green and lilac into the flame edges and spits without warning. Turn a piece over before you commit — the underside is always wetter than it looks, and the steam it makes is half the character of this fire.',
  },
  wildlife: [
    {
      id: 'sanderling',
      label: 'Sanderlings',
      shyness: 0.55,
      curiosity: 0.3,
      window: ['dusk', 'dawn'],
      attractedBy: ['water-edge', 'quiet'],
      repelledBy: ['footsteps', 'flashlight'],
      canPersist: false,
      investigatesObjects: false,
      traces: ['stitched lines of tiny prints along the wet sand'],
      note: 'A dozen of them running the wave edge as one animal, reversing all at once.',
    },
    {
      id: 'shore_fox',
      label: 'Beach fox',
      shyness: 0.62,
      curiosity: 0.9,
      window: ['early-night', 'deep-night'],
      attractedBy: ['food-smell', 'marshmallow-smell', 'stillness', 'firelight'],
      repelledBy: ['sudden-movement', 'camera-flash'],
      canPersist: true,
      investigatesObjects: true,
      traces: ['neat prints along the log', 'a marshmallow bag dragged two metres and abandoned', 'scat on the highest point of the berm'],
      note: 'Works the wrack line every night on the same schedule. Sits down out of arm-reach and watches you cook. Has a notch in one ear.',
    },
    {
      id: 'harbour_seal',
      label: 'Harbour seal',
      shyness: 0.8,
      curiosity: 0.75,
      window: ['deep-night'],
      attractedBy: ['singing', 'radio-music', 'firelight'],
      repelledBy: ['splashing', 'voices'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a wet drag mark above the tide line at dawn'],
      note: 'A head in the water past the break, holding station. If the radio is on, it stays longer. Nobody can prove that.',
    },
    {
      id: 'ghost_crab',
      label: 'Sand crabs',
      shyness: 0.4,
      curiosity: 0.5,
      window: ['deep-night'],
      attractedBy: ['crumbs', 'moonlight'],
      repelledBy: ['flashlight', 'footsteps'],
      canPersist: false,
      investigatesObjects: true,
      traces: ['a ring of excavated sand around a dropped crumb'],
      note: 'Move sideways out of the dark, freeze in the flashlight beam, and are simply gone when it moves off.',
    },
  ],
  ambience: {
    wind: { character: 'onshore', baseLevel: 0.62, gustiness: 0.55, material: 'dune grass and the hollow underside of the log' },
    insectDensity: 0.08,
    insectNote: 'Almost none — too cold, too salt. A single sand fly ticking against the lantern glass counts as the insect layer here.',
    waterPresence: 0.95,
    reverb: 'clearing',
    reverbNote: 'Open and forward, with no returns from seaward at all. Sound thrown at the water never comes back, which is unnerving in a pleasant way.',
    distantEvents: [
      { id: 'foghorn', label: 'Foghorn', weight: 5, minGapSeconds: 200, note: 'Two notes, low, from somewhere the light is not.' },
      { id: 'log_boom', label: 'A log rolls in the surf', weight: 4, minGapSeconds: 150, note: 'A deep knock you feel through the sand before you hear it.' },
      { id: 'gull_argument', label: 'Gulls arguing offshore', weight: 3, minGapSeconds: 240, note: 'Brief, ridiculous, over as soon as it starts.' },
      { id: 'boat_engine', label: 'A boat engine crossing', weight: 2, minGapSeconds: 420, note: 'Diesel, unhurried, tracking left to right and never getting closer.' },
    ],
    nightFloorDb: -38,
  },
  activities: [
    { id: 'fire-tending', label: 'Tend the fire', prominence: 'notable', note: 'Wind management is the whole game — the log, the pit, and where you stand.' },
    { id: 'stone-skipping', label: 'Skip stones', prominence: 'notable', note: 'Terrible conditions and excellent stones. Two skips is a triumph.' },
    { id: 'driftwood-gathering', label: 'Gather driftwood', prominence: 'notable', note: 'A real walk down the wrack line with a flashlight, choosing pieces.' },
    { id: 'tide-pooling', label: 'Tide pools', prominence: 'signature', note: 'North end, low water only. Anemones close as your light passes; a hermit crab wearing a bottle cap lives in the third pool and is there every visit.' },
    { id: 'stargazing', label: 'Stargaze', prominence: 'available', note: 'The most open sky in the catalogue when the marine layer lifts — which it does about one visit in three.' },
    { id: 'photography', label: 'Photograph', prominence: 'signature', note: 'The point light plus fire plus fog is the best product-photography lighting in the set. The sandwich against wet sand is the shot.' },
    { id: 'radio', label: 'Radio', prominence: 'notable', note: 'Sea path propagation. Stations from impossibly far away arrive clean and then vanish.' },
    { id: 'flashlight', label: 'Flashlight', prominence: 'available', note: 'The beam dies in the salt haze about eight metres out. Everything past that is rumour.' },
    { id: 'wildlife-watching', label: 'Watch for wildlife', prominence: 'available', note: 'The fox is on a schedule. You are not.' },
  ],
  radio: {
    stations: [
      { id: 'coast_wx', dial: 162.55, band: 'fm', name: 'Continuous Marine Forecast', character: 'weather-service', reception: 0.94, note: 'A synthesised voice giving wave heights for waters you cannot name. Loops every eight minutes. Deeply soothing.' },
      { id: 'kdrf_1013', dial: 101.3, band: 'fm', name: 'KDRF — Driftwood', character: 'lofi', reception: 0.71, note: 'Reverb-drowned guitar and tape hiss, recorded in a room with a hard floor. The only station that ever plays anything twice.' },
      { id: 'skip_760', dial: 760, band: 'am', name: 'A station from far inland', character: 'community', reception: 0.35, note: 'Arrives on a sea path after midnight, fully clear, talking about traffic on roads that are seven hundred miles away.' },
      { id: 'numbers_6840', dial: 6840, band: 'shortwave', name: '6840 kHz', character: 'strange', reception: 0.28, note: 'A woman reading five-digit groups in a level voice, then a music box, then carrier, then nothing. Not addressed to you.' },
      { id: 'harbour_chat', dial: 1610, band: 'am', name: 'Harbour information', character: 'environmental', reception: 0.55, note: 'Tide tables and a note about the ramp being closed, read by someone who has read it many times.' },
    ],
    baseReception: 0.62,
    receptionNote: 'Everything seaward comes in strong and everything landward is blocked by the headland. After midnight the AM band opens up absurdly.',
    betweenStations: 'A wash of static that breathes in time with the surf, because the receiver AGC is riding the noise floor.',
  },
  secrets: [
    {
      id: 'ls_float_with_a_name',
      title: 'The float with a name on it',
      discovery: 'A glass fishing float in the wrack line, netted, with a name and a date painted on the inside of the glass.',
      telling: 'The date is next year. The paint is very old. It is almost certainly a coincidence and it is very hard to put down.',
      channels: ['strange-objects'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.22,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ls_light_stutters',
      title: 'The night the light stutters',
      discovery: 'The point light misses a turn. Then another. Then it resumes, exactly on the nine-second beat, as if it had never stopped.',
      telling: 'For those forty seconds the beach is genuinely dark and the fire is the only thing in the world, and it is the coziest the game ever gets.',
      channels: ['campsite-changes', 'distant-sounds'],
      oneTime: true,
      leavesEvidence: 'Afterwards, a hand-lettered card appears in the plank walk gap: OUTAGE LOGGED — 40 SEC — NO CAUSE FOUND.',
      rarity: 0.12,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ls_boot_in_the_planks',
      title: 'The boot in the planks',
      discovery: 'The heel wedged in the plank walk comes free if you work at it.',
      telling: 'Underneath is a folded permit for a campsite at a different environment entirely, stamped and never used.',
      channels: ['notes', 'strange-objects'],
      oneTime: true,
      leavesEvidence: 'The gap stays empty afterward, and the permit turns up pressed in the Passport with sand still in the fold.',
      rarity: 0.28,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ls_fox_brings_something',
      title: 'The fox brings something',
      discovery: 'After enough visits where you sat still and let it work the wrack line, the fox leaves an object on the log.',
      telling: 'A bottle cap, a spoon, once a key. It never takes anything of yours. It just seems to have decided this is a place where things get put.',
      channels: ['wildlife-behaviour', 'campsite-changes'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.15,
      optional: true,
      gatesNothing: true,
    },
  ],
  machine: {
    quirkWeights: { 'rough-fan': 3, 'warm-latch': 2.5, 'early-frost': 2, 'loud-compressor': 2, 'proud-badge': 1.5 },
    flavourNote:
      'Salt has been at this unit for years. The badge screws are rust-haloed, the fan bearing sings on start-up, and the enamel above the door has gone chalky. It still runs perfectly, which is somehow the point.',
    stickerHint: 'HANDLE COLD SURFACES WITH CARE, bubbled and lifting at every edge.',
    frostNote: 'Frost fights the salt damp and loses at the corners, so the window frosts in a clean oval with soft grey edges.',
  },
  procedural: {
    seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'wrack', 'tide', 'machine'],
    variations: [
      { id: 'tide_state', label: 'Tide line position', range: { min: 12, max: 46 }, unit: 'metres from the log', note: 'Set at arrival and held for the session. Governs tide-pool access and how much beach exists.' },
      { id: 'wrack_composition', label: 'Wrack line contents', range: { min: 6, max: 22 }, unit: 'objects', note: 'Kelp, rope, floats, feathers, one implausible item. Fully reshuffled between visits.' },
      { id: 'marine_layer', label: 'Marine layer height', range: { min: 0, max: 1 }, unit: 'normalised', note: 'Drives fog density, star visibility and how the point light reads.' },
      { id: 'driftwood_size', label: 'Largest available driftwood piece', range: { min: 0.4, max: 1.4 }, unit: 'relative mass', note: 'Some nights the beach gives you a log; some nights, kindling and patience.' },
      { id: 'fox_schedule', label: 'Fox arrival offset', range: { min: 90, max: 600 }, unit: 'seconds after arrival', note: 'Same fox, different hour.' },
    ],
    invariants: [
      'The big log, its root wad, and the still pocket behind it.',
      'The nine-second light on the point.',
      'The broken plank walk.',
      'The hermit crab in the third tide pool.',
    ],
  },
  discovery: {
    weight: 10,
    affinities: { 'maritime-west': 2.2, 'maritime-east': 1.9, boreal: 1.1, unknown: 1.2, highland: 0.7, 'arid-interior': 0.5, 'continental-interior': 0.6, mediterranean: 1.2, 'humid-subtropical': 0.9 },
    note: 'Weighted toward coastal players, still freely reachable inland — a landlocked player meets this beach sooner or later and it should feel like a trip.',
  },
  performance: {
    cost: 'light',
    midTierDrawCalls: 52,
    midTierTriangles: 21000,
    dynamicLights: 4,
    lowTierCuts: [
      'Dune grass scatter drops to 30% and loses per-blade wind.',
      'Surf foam becomes a scrolling texture band rather than particles.',
      'The point light stops casting and becomes an unshadowed glow cone.',
      'Wrack-line object count 22 → 8.',
    ],
    note: 'Very few draw calls; the cost is all in the surf shader and the particle-driven spray. The cheapest environment to run and one of the best-looking, which is what flat geometry plus one strong light does.',
  },
};
