/**
 * Meltwater Cirque — above the trees, beside a tarn, in air that is too thin
 * to hold sound.
 *
 * The hardest fire in the catalogue and deliberately so: krummholz burns fast
 * and cold, wind arrives in katabatic pushes off the snowfield, and the only
 * good ember bed comes from planning. It is never punishing — embers always
 * recover — but it is the site where fire tending is most obviously a skill.
 */
export const MELTWATER_CIRQUE = {
    id: 'meltwater_cirque',
    name: 'Meltwater Cirque',
    tagline: 'A tarn like a held breath, three snowfields above it, and a fire that has to be argued with.',
    inspiration: 'A glacial cirque above the treeline in a high western range — slabbed granite, a bowl of meltwater, and the last twisted pines lying flat against the rock.',
    biomeTags: ['alpine', 'glacial-cirque', 'above-treeline', 'granite'],
    character: {
        temperature: 'cold',
        moisture: 'balanced',
        altitude: 'alpine',
        treeCover: 'none',
        water: 'tarn',
        eeriness: 3,
    },
    arrival: {
        approach: 'Switchbacks in scree that you hear more than see, then a long ramp of bare granite with a chain of small cairns on it. The last of the trees gives up behind you and does not follow.',
        firstHeard: 'Meltwater under the talus — running somewhere below the rock you are standing on, with no visible source and no visible outlet.',
        firstSeen: 'Snow. Three grey-white patches high on the headwall, holding light long after everything else has let go of it.',
        underfoot: 'Granite, then gravel that rolls, then a flat slab that rings very slightly under a boot heel.',
        arrivalBeat: 'You come over the lip and the whole bowl is below you at once — tarn, headwall, snow, and one small orange fire at the far edge of the water with its reflection running all the way across to your feet.',
        walkSeconds: { min: 34, max: 52 },
    },
    scene: {
        ground: 'granite-slab',
        groundNote: 'Glacier-polished granite in wide plates, gravel in the joints, and one long striation scored into the rock that points at the tarn.',
        vegetation: [
            { kitId: 'kit_krummholz', label: 'Krummholz pine', density: 2.5, heightRange: { min: 0.3, max: 1.6 }, lowTierDrop: false, note: 'Ground-hugging, flagged, older than anything else in the catalogue. They look like they are bracing.' },
            { kitId: 'kit_alpine_cushion', label: 'Cushion plants', density: 26, heightRange: { min: 0.03, max: 0.15 }, lowTierDrop: true, note: 'Tight green buttons in every crack. A whole meadow that comes up to your ankle.' },
            { kitId: 'kit_heather_alpine', label: 'Alpine heather', density: 12, heightRange: { min: 0.1, max: 0.4 }, lowTierDrop: true, note: 'Rust-and-green mats on the shelf above the tarn.' },
        ],
        landmarks: [
            { id: 'headwall', label: 'The headwall', kind: 'natural', handcrafted: true, note: 'Four hundred metres of grey rock closing the bowl. It is the ceiling, the wall, and the reason for the echo.' },
            { id: 'the_tarn', label: 'The tarn', kind: 'water', handcrafted: true, note: 'Perfectly still, absurdly clear, and cold enough that your hand aches in four seconds. Reflects the headwall like a hinge.' },
            { id: 'shelter_wall', label: 'The stacked shelter wall', kind: 'built', handcrafted: true, note: 'A waist-high horseshoe of dry-stacked rocks built by climbers, with a flat capstone that is the best seat in the environment.' },
            { id: 'snow_patches', label: 'The three snowfields', kind: 'natural', handcrafted: true, note: 'High on the headwall. They shrink and grow between visits and never disappear.' },
            { id: 'boot_cache', label: 'The cache under the capstone', kind: 'abandoned', handcrafted: true, note: 'A tin under the flat rock with a pencil and a register book in it.' },
        ],
        elevation: 'basin',
        elevationNote: 'A hanging bowl with a lip. Cold air pours over the lip and down the ramp all night — the site has a direction, and the fire knows it.',
        water: {
            kind: 'tarn',
            label: 'The tarn',
            widthM: 90,
            flow: 'still',
            clarity: 0.97,
            fishable: false,
            skippable: true,
            note: 'Too cold and too young for fish. Skipping stones across it makes a sound like a struck wire, which is the best reason to be here.',
        },
        drawDistanceM: 190,
        fog: { colour: '#20272e', density: 0.006, note: 'Thin and clean, except when cloud sits in the bowl, and then you cannot see the far side of the tarn at all.' },
        nightPalette: {
            zenith: '#050810',
            horizon: '#182230',
            ground: '#3c3e42',
            foliage: '#20291f',
            rock: '#4b4d51',
            water: '#101820',
            fireGlow: '#ff9d55',
            moonlight: '#c2d2e6',
            shadow: '#070a0e',
        },
        skyOpenness: 0.72,
        walkableRadiusM: 55,
    },
    weather: {
        id: 'meltwater-cirque',
        weights: { clear: 5, 'high-cloud': 3, wind: 4, fog: 3, overcast: 2, snow: 2, 'snow-squall': 1, 'light-rain': 1 },
        baseTempC: 2,
        baseWind: 2.6,
        exposure: 0.75,
        skyEventChance: 0.22,
        skyEvents: ['meteor-shower', 'aurora'],
        transitionSeconds: 140,
    },
    weatherCharacter: {
        temperatureNote: 'Cold, and it changes fast. Your breath is visible from the moment you arrive, and the side of you facing the tarn is always colder than the side facing the fire.',
        windNote: 'Katabatic: it drains off the snowfields in slow heavy pushes, roughly every few minutes, and dies between them.',
        exposureNote: 'The stacked shelter wall exists for exactly one reason and using it correctly is the difference between a fire and a smoke signal.',
        nightRangeC: { min: -6, max: 6 },
    },
    fuel: {
        sources: [
            { woodId: 'pine', weight: 5, foundAs: 'Dead krummholz limbs, dense as bone and no thicker than a wrist.', moistureBias: -0.06 },
            { woodId: 'birch', weight: 3, foundAs: 'A bundle of dwarf birch someone hauled up and cached under the wall.', moistureBias: 0.02 },
            { woodId: 'aspen', weight: 2, foundAs: 'Driftwood off the tarn shore — floated in, then frozen and thawed a hundred times.', moistureBias: 0.16 },
        ],
        note: 'Nothing here is big. The fire is built from a hundred small dense pieces, it burns hot and fast, and it will not make a bed unless you feed it patiently and keep it out of the katabatic push. Get it right and the coals sit in the rock hollow radiating upward like a hotplate.',
    },
    wildlife: [
        {
            id: 'pika',
            label: 'Pika',
            shyness: 0.5,
            curiosity: 0.6,
            window: ['dusk', 'dawn'],
            attractedBy: ['stillness', 'quiet'],
            repelledBy: ['footsteps', 'sudden-movement'],
            canPersist: true,
            investigatesObjects: false,
            traces: ['a haypile of cut alpine plants drying on a flat rock', 'droppings on the same lookout stone every visit'],
            note: 'A round grey thing that appears on a rock, makes one absurd bleat, and is not there when you look back. Owns this talus and knows it.',
        },
        {
            id: 'rosy_finch',
            label: 'Rosy finches',
            shyness: 0.65,
            curiosity: 0.45,
            window: ['dawn', 'dusk'],
            attractedBy: ['crumbs', 'quiet', 'warmth'],
            repelledBy: ['wind', 'sudden-movement'],
            canPersist: false,
            investigatesObjects: true,
            traces: ['prints in the snow patch margin', 'crumbs gone from the capstone'],
            note: 'Feed on the snowfield edges. A loose flock that comes over the lip in one piece and lands like thrown gravel.',
        },
        {
            id: 'ermine',
            label: 'Ermine',
            shyness: 0.8,
            curiosity: 0.95,
            window: ['deep-night', 'pre-dawn'],
            attractedBy: ['stillness', 'crumbs', 'food-smell'],
            repelledBy: ['flashlight', 'voices', 'camera-flash'],
            canPersist: true,
            investigatesObjects: true,
            traces: ['a line of paired prints crossing a snow patch and stopping at the wall', 'a glove moved from where you left it'],
            note: 'Pours between the rocks like something spilled. Comes right into the shelter wall if you have been still for minutes, stands up to look at you, and leaves.',
        },
        {
            id: 'nutcracker',
            label: 'Clark’s nutcracker',
            shyness: 0.4,
            curiosity: 0.85,
            window: ['dusk', 'dawn'],
            attractedBy: ['crumbs', 'food-smell', 'voices'],
            repelledBy: ['sudden-movement'],
            canPersist: true,
            investigatesObjects: true,
            traces: ['a graham cracker corner wedged into a crack in the granite, cached for later'],
            note: 'Grey, loud, entirely unafraid, and remembers thousands of hiding places. Will absolutely take something off the capstone while you watch.',
        },
    ],
    ambience: {
        wind: { character: 'katabatic', baseLevel: 0.34, gustiness: 0.75, material: 'bare rock and the low heather, with nothing to rustle' },
        insectDensity: 0.06,
        insectNote: 'Effectively none. A single moth working the firelight, badly, and mosquitoes only in the first hour after dusk.',
        waterPresence: 0.4,
        reverb: 'canyon',
        reverbNote: 'The headwall returns everything, once, with about a second and a half of delay and a slightly darker tone. Stone skipping across the tarn comes back as a descending chirp.',
        distantEvents: [
            { id: 'rockfall_headwall', label: 'Rockfall on the headwall', weight: 4, minGapSeconds: 260, note: 'A clatter high up, then the sound of it arriving somewhere you cannot see.' },
            { id: 'ice_groan', label: 'The snowfield settles', weight: 3, minGapSeconds: 400, note: 'A low compressed groan, felt more than heard. Nothing moves.' },
            { id: 'meltwater_surge', label: 'The under-talus water changes pitch', weight: 5, minGapSeconds: 120, note: 'The invisible stream drops a note and stays there for a while.' },
            { id: 'high_wind_line', label: 'Wind on the ridge above', weight: 4, minGapSeconds: 90, note: 'You hear it arrive across the bowl for two full seconds before it reaches you.' },
        ],
        nightFloorDb: -60,
    },
    activities: [
        { id: 'fire-tending', label: 'Tend the fire', prominence: 'signature', note: 'The most demanding and most rewarding fire in the catalogue. Windbreak placement, small fuel, and patience.' },
        { id: 'stone-skipping', label: 'Skip stones', prominence: 'signature', note: 'Glass-still water, a hard wall behind it, and each skip returning as a separate note. Genuinely the deep one — people will do this for ten minutes.' },
        { id: 'stargazing', label: 'Stargaze', prominence: 'notable', note: 'The headwall eats a third of the sky, and the rest is exceptional. Aurora is possible here.' },
        { id: 'binoculars', label: 'Binoculars', prominence: 'available', note: 'For the snowfields, for the ermine, and for the lights that sometimes move on the ridge.' },
        { id: 'photography', label: 'Photograph', prominence: 'notable', note: 'The tarn reflection doubles everything, including the machine. Frost on the sandwich against granite is very good.' },
        { id: 'radio', label: 'Radio', prominence: 'available', note: 'Line of sight to distant valleys. Two clear stations, nothing in between, and one that is only there when the wind drops.' },
        { id: 'flashlight', label: 'Flashlight', prominence: 'available', note: 'Reaches all the way across the tarn and lights the far shore, which is further than a flashlight has any right to reach.' },
        { id: 'snow-tracking', label: 'Read the snow', prominence: 'notable', note: 'Every animal that crossed the patch since the last melt is written on it, including yours from last visit if it has not thawed.' },
        { id: 'cairn-reading', label: 'The register tin', prominence: 'signature', note: 'A pencil and a book under the capstone. Names, dates, weather, one drawing of the headwall, and a line of handwriting you are fairly sure you recognise.' },
        { id: 'wildlife-watching', label: 'Watch for wildlife', prominence: 'available', note: 'The ermine comes for stillness alone.' },
    ],
    radio: {
        stations: [
            { id: 'kalp_895', dial: 89.5, band: 'fm', name: 'KALP — Valley Public', character: 'ambient', reception: 0.66, note: 'Overnight classical with the volume too low and the announcer half asleep. Arrives over the ridge from a town you can almost see.' },
            { id: 'noaa_alpine', dial: 162.475, band: 'fm', name: 'Mountain Forecast', character: 'weather-service', reception: 0.8, note: 'Ridge-top winds, freezing levels, and avalanche notes for a season that is not now. Reads like poetry when you are cold.' },
            { id: 'repeater_ghost', dial: 146.52, band: 'fm', name: 'The calling frequency', character: 'strange', reception: 0.3, note: 'Empty most of the time. Once in a while somebody says a callsign and a single word, and then it is empty again.' },
            { id: 'kicy_1122', dial: 112.2, band: 'am', name: 'Aeronautical beacon', character: 'environmental', reception: 0.72, note: 'A three-letter identifier in Morse, forever, from an airfield ninety kilometres away. Weirdly companionable.' },
        ],
        baseReception: 0.55,
        receptionNote: 'Everything arrives across the top of the bowl. Stand on the lip and the dial fills up; sit by the fire and half of it goes away.',
        betweenStations: 'Cold, clean hiss with almost no crackle — there is no weather between you and the transmitter, just air.',
    },
    secrets: [
        {
            id: 'mc_register_tin',
            title: 'The register',
            discovery: 'Lift the capstone. There is a pencil, a tin, and a book that goes back further than the tin looks capable of surviving.',
            telling: 'Names and dates and one-line weather notes. Somebody signs it every few years with only initials and a small drawing of the headwall, and the drawing gets slightly better each time.',
            channels: ['notes', 'recurring-figures'],
            oneTime: false,
            leavesEvidence: null,
            rarity: 0.55,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'mc_thing_in_the_tarn',
            title: 'The shape under the tarn',
            discovery: 'With a flashlight on the water on a dead-still night, something rectangular is visible on the bottom near the outlet.',
            telling: 'It is a pack frame, aluminium, upright, three metres down in water so clear it looks like a metre. Nothing else. Somebody, a long time ago, put their pack down.',
            channels: ['strange-objects'],
            oneTime: false,
            leavesEvidence: null,
            rarity: 0.2,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'mc_the_light_on_the_ridge',
            title: 'The headlamp on the ridge',
            discovery: 'A small white light works its way along the ridgeline, stops for a while, and goes on.',
            telling: 'It never comes down and it never signals. If you point your own flashlight at it, it stops. If you turn yours off, it goes on moving. That is the whole of it.',
            channels: ['recurring-figures'],
            oneTime: false,
            leavesEvidence: null,
            rarity: 0.14,
            optional: true,
            gatesNothing: true,
        },
        {
            id: 'mc_the_thaw',
            title: 'The night the middle snowfield lets go',
            discovery: 'A long grinding collapse high on the headwall, at three in the morning, that goes on for eleven seconds.',
            telling: 'Nothing reaches the bowl. In the morning the middle snowfield is a different shape and there is a fan of fresh grey debris on the talus that was not there.',
            channels: ['distant-sounds', 'campsite-changes'],
            oneTime: true,
            leavesEvidence: 'The debris fan is permanent, and the middle snowfield keeps its new shape on every future visit.',
            rarity: 0.1,
            optional: true,
            gatesNothing: true,
        },
    ],
    machine: {
        quirkWeights: { 'early-frost': 3.5, 'sticky-door': 2.5, 'slow-amber': 2, 'rough-fan': 1.5 },
        flavourNote: 'This unit barely has to work. In air this cold the chamber is already halfway there, the compressor loafs, and the whole run sounds noticeably lazier than it does anywhere else — which regular players notice immediately and find oddly touching.',
        stickerHint: 'TESTED · PASSED with a second, older inspection tag underneath showing through the frost.',
        frostNote: 'Frost never leaves. It builds through the run, survives the door opening, and is still on the left panel an hour later.',
    },
    procedural: {
        seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'snow', 'tarn', 'machine'],
        variations: [
            { id: 'snowfield_extent', label: 'Snowfield coverage', range: { min: 0.25, max: 1 }, unit: 'normalised', note: 'How much of the headwall still holds snow. Drives katabatic strength and snow-tracking availability.' },
            { id: 'tarn_stillness', label: 'Tarn surface stillness', range: { min: 0.3, max: 1 }, unit: 'normalised', note: 'Governs the reflection, the stone-skipping tone, and whether the pack frame is visible.' },
            { id: 'cloud_in_the_bowl', label: 'Cloud sitting in the cirque', range: { min: 0, max: 1 }, unit: 'probability', note: 'When it happens, draw distance collapses to twenty metres and the site becomes a room.' },
            { id: 'krummholz_fuel', label: 'Available krummholz deadwood', range: { min: 6, max: 20 }, unit: 'pieces', note: 'Never zero.' },
            { id: 'register_entries', label: 'New entries in the register', range: { min: 0, max: 4 }, unit: 'entries', note: 'People have been here since you were last here. Sometimes.' },
        ],
        invariants: [
            'The headwall and the three snowfields.',
            'The stacked shelter wall and its capstone.',
            'The striation pointing at the tarn.',
            'The pack frame on the bottom.',
        ],
    },
    discovery: {
        weight: 8,
        affinities: { highland: 2.6, boreal: 1.3, 'maritime-west': 1.1, 'continental-interior': 0.9, unknown: 1.1, 'arid-interior': 0.8, mediterranean: 0.9, 'maritime-east': 0.8, 'humid-subtropical': 0.5 },
        note: 'A demanding, rarer site. Weighted for mountain regions but reachable by anyone — the fire lesson here is worth the trip.',
    },
    performance: {
        cost: 'moderate',
        midTierDrawCalls: 63,
        midTierTriangles: 39000,
        dynamicLights: 4,
        lowTierCuts: [
            'Tarn reflection becomes a static cube reflection instead of a live render pass — this is the single biggest saving in the environment.',
            'Cushion-plant and heather scatter drop to 20%.',
            'Headwall LOD steps down two levels; at 190m nobody can tell.',
            'Breath vapour particles drop from per-breath puffs to a single looping sprite.',
        ],
        note: 'The live water reflection is the whole cost. Everything else here is large simple rock, which is the cheapest thing a PS1 renderer can draw.',
    },
};
//# sourceMappingURL=meltwater-cirque.js.map