import type { EnvironmentManifest } from '../schema.js';

/**
 * Pine Hollow — the baseline. The campground everyone half-remembers.
 *
 * Deliberately the least strange environment in the catalogue: it is the one
 * a first-time player is most likely to meet, and its job is to be warm,
 * legible and completely unthreatening while still having corners.
 */
export const PINE_HOLLOW: EnvironmentManifest = {
  id: 'pine_hollow',
  name: 'Pine Hollow',
  tagline: 'A numbered site in a bowl of second-growth pine, one bar of a creek running behind it.',
  inspiration:
    'A mid-elevation national-forest loop campground in the western ranges — numbered posts, a steel fire ring, a bear box with the paint worn off the latch.',
  biomeTags: ['montane-conifer', 'creekside', 'managed-campground', 'second-growth'],
  character: {
    temperature: 'mild',
    moisture: 'damp',
    altitude: 'upland',
    treeCover: 'dense',
    water: 'creek',
    eeriness: 2,
  },
  arrival: {
    approach:
      'A gravel spur off the loop road, sloping down between two rows of lodgepole. The gravel gives way to needle duff about forty paces in, and the road noise stops all at once.',
    firstHeard:
      'The creek — not water exactly, more a steady sheet of white noise that you mistake for wind until you notice it never changes.',
    firstSeen:
      'The reflector on the site post, catching your flashlight from the dark and throwing back one flat orange rectangle.',
    underfoot:
      'Gravel, then needles that give under your weight and let out a dry pine smell each step.',
    arrivalBeat:
      'The trees open into a bowl maybe fifteen metres across. The fire ring is already going low and orange, and the SM-01 stands at the edge of the light with its idle lamp on.',
    walkSeconds: { min: 22, max: 38 },
  },
  scene: {
    ground: 'pine-duff',
    groundNote:
      'Deep rust-brown needle litter over compacted dirt, worn to bare soil in a ring around the fire and along the path to the creek.',
    vegetation: [
      {
        kitId: 'kit_lodgepole',
        label: 'Lodgepole pine',
        density: 14,
        heightRange: { min: 9, max: 21 },
        lowTierDrop: false,
        note: 'Straight, branchless for the first four metres. Reads as columns, which is what makes the site feel like a room.',
      },
      {
        kitId: 'kit_young_fir',
        label: 'Young fir infill',
        density: 22,
        heightRange: { min: 0.8, max: 3.5 },
        lowTierDrop: true,
        note: 'Waist-to-shoulder height. Their only job is to hide the edges of the walkable area without a wall.',
      },
      {
        kitId: 'kit_bracken',
        label: 'Bracken and huckleberry',
        density: 46,
        heightRange: { min: 0.2, max: 0.9 },
        lowTierDrop: true,
        note: 'Thickest along the creek path. Catches firelight on the topmost fronds only.',
      },
    ],
    landmarks: [
      {
        id: 'site_post_11',
        label: 'Site post 11',
        kind: 'signage',
        handcrafted: true,
        note: 'A weathered post with a reflector and a laminated card whose ink has gone violet. The site number never changes.',
      },
      {
        id: 'bear_box',
        label: 'Steel bear box',
        kind: 'built',
        handcrafted: true,
        note: 'Olive drab, dented on the top left, latch worn to bare metal. Firewood is stacked against its north side.',
      },
      {
        id: 'leaning_snag',
        label: 'The leaning snag',
        kind: 'natural',
        handcrafted: true,
        note: 'A dead pine caught in the crotch of a living one, at maybe fifteen degrees. It creaks in wind and never falls.',
      },
      {
        id: 'creek_stones',
        label: 'Creek stepping stones',
        kind: 'water',
        handcrafted: false,
        note: 'Three flat stones across the narrow point. The middle one wobbles.',
      },
    ],
    elevation: 'basin',
    elevationNote:
      'A shallow bowl. The ground rises gently on three sides, which is why the smoke pools and why the site is so quiet.',
    water: {
      kind: 'creek',
      label: 'The creek behind the site',
      widthM: 2.4,
      flow: 'running',
      clarity: 0.85,
      fishable: true,
      skippable: false,
      note: 'Ankle-deep, fast, loud out of proportion to its size. Small trout hold behind the stones.',
    },
    drawDistanceM: 48,
    fog: { colour: '#1b2430', density: 0.028, note: 'Cold blue haze that thickens after midnight and pools in the bowl.' },
    nightPalette: {
      zenith: '#0a1018',
      horizon: '#1d2733',
      ground: '#2b2119',
      foliage: '#1e2a20',
      rock: '#3a3a38',
      water: '#22303a',
      fireGlow: '#ff9b47',
      moonlight: '#8fa6c4',
      shadow: '#080c11',
    },
    skyOpenness: 0.32,
    walkableRadiusM: 34,
  },
  weather: {
    id: 'pine-hollow',
    weights: { clear: 5, 'high-cloud': 4, overcast: 3, 'light-rain': 2, rain: 1, fog: 2, wind: 1 },
    baseTempC: 11,
    baseWind: 0.9,
    exposure: 0.3,
    skyEventChance: 0.1,
    skyEvents: ['meteor-shower'],
    transitionSeconds: 250,
  },
  weatherCharacter: {
    temperatureNote:
      'Warm at the fire, sharply cold three steps back. The bowl holds cold air after midnight.',
    windNote: 'Rarely more than a stir in the tops. You hear wind before you feel it.',
    exposureNote: 'The pit is sheltered on three sides — a flare here is the fire, not the weather.',
    nightRangeC: { min: 4, max: 15 },
  },
  fuel: {
    sources: [
      { woodId: 'pine', weight: 6, foundAs: 'Split rounds stacked against the bear box, sold on the honour system.', moistureBias: -0.04 },
      { woodId: 'oak', weight: 2, foundAs: 'Two heavy pieces someone left behind, half buried in duff.', moistureBias: 0.06 },
      { woodId: 'aspen', weight: 3, foundAs: 'Deadfall limbs from the edge of the bowl, snapping dry.', moistureBias: 0 },
    ],
    note:
      'Pine here pops and throws sparks and smells like the whole place; the two oak pieces are the secret — put them on early and the ember bed lasts the entire night.',
  },
  wildlife: [
    {
      id: 'douglas_squirrel',
      label: 'Pine squirrel',
      shyness: 0.35,
      curiosity: 0.8,
      window: ['dusk', 'dawn'],
      attractedBy: ['crumbs', 'quiet', 'food-smell'],
      repelledBy: ['sudden-movement', 'flashlight'],
      canPersist: true,
      investigatesObjects: true,
      traces: ['a stripped cone on the picnic table', 'scattered cone scales', 'a moved marshmallow bag'],
      note: 'Loud out of all proportion. Scolds you from a branch for a full minute, then forgets why.',
    },
    {
      id: 'flying_squirrel',
      label: 'Northern flying squirrel',
      shyness: 0.88,
      curiosity: 0.55,
      window: ['deep-night'],
      attractedBy: ['stillness', 'quiet', 'moonlight'],
      repelledBy: ['voices', 'radio-music', 'flashlight'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a scratch of claws on bark somewhere above', 'a soft thump on the bear box lid'],
      note: 'Only appears for players who have been genuinely still for a while. Crosses the gap between two trunks in one silent line and is gone.',
    },
    {
      id: 'saw_whet_owl',
      label: 'Saw-whet owl',
      shyness: 0.95,
      curiosity: 0.2,
      window: ['early-night', 'deep-night'],
      attractedBy: ['quiet', 'stillness'],
      repelledBy: ['compressor-noise', 'voices'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a single pellet under the leaning snag'],
      note: 'A repeating tin-whistle note from the dark, always further away than it sounds. Seen perhaps once in many visits.',
    },
    {
      id: 'deer_mouse',
      label: 'Deer mouse',
      shyness: 0.6,
      curiosity: 0.9,
      window: ['early-night', 'deep-night'],
      attractedBy: ['crumbs', 'food-smell', 'warmth'],
      repelledBy: ['sudden-movement'],
      canPersist: false,
      investigatesObjects: true,
      traces: ['tiny prints in the duff', 'a graham crumb moved fifteen centimetres for no reason'],
      note: 'Runs the same route along the log every time, as if it were a corridor.',
    },
  ],
  ambience: {
    wind: { character: 'breathing', baseLevel: 0.22, gustiness: 0.3, material: 'pine needles, thirty feet up' },
    insectDensity: 0.45,
    insectNote: 'A modest crick-and-pause chorus that stops dead if you stand up too fast, then restarts one voice at a time.',
    waterPresence: 0.55,
    reverb: 'openForest',
    reverbNote: 'Short, dry, absorbed. Trunks give a faint slap-back; the duff eats everything else.',
    distantEvents: [
      { id: 'far_car', label: 'A car on the loop road', weight: 3, minGapSeconds: 240, note: 'Tyres on gravel, a door, then nothing. Never arrives.' },
      { id: 'far_laugh', label: 'Laughter from another site', weight: 4, minGapSeconds: 180, note: 'Two people, too far to make out words. Warm, not intrusive.' },
      { id: 'snag_creak', label: 'The leaning snag creaks', weight: 5, minGapSeconds: 90, note: 'A long wooden complaint from directly overhead when the tops move.' },
      { id: 'far_owl', label: 'The owl, further off', weight: 2, minGapSeconds: 300, note: 'The same tin-whistle note, from a different direction than last time.' },
    ],
    nightFloorDb: -52,
  },
  activities: [
    { id: 'fire-tending', label: 'Tend the fire', prominence: 'signature', note: 'The oak pieces reward a player who plans an hour ahead.' },
    { id: 'fishing', label: 'Fish the creek', prominence: 'available', note: 'Small trout behind the stones. Catch-and-release, and mostly an excuse to sit on a rock.' },
    { id: 'stargazing', label: 'Stargaze', prominence: 'available', note: 'Only a ragged patch of sky through the crowns — which makes the meteor that crosses it feel personal.' },
    { id: 'photography', label: 'Photograph', prominence: 'notable', note: 'Firelight on straight trunks. The most forgiving light in the catalogue.' },
    { id: 'radio', label: 'Radio', prominence: 'available', note: 'Decent FM in the bowl if you angle the aerial toward the gap in the ridge.' },
    { id: 'flashlight', label: 'Flashlight', prominence: 'available', note: 'The reflector on the site post answers from anywhere in the site.' },
    { id: 'wildlife-watching', label: 'Watch for wildlife', prominence: 'notable', note: 'Stillness is the entire mechanic here.' },
    { id: 'foraging', label: 'Gather kindling', prominence: 'available', note: 'Dry twigs under the young firs, always.' },
    { id: 'moth-sheet', label: 'Hang the moth sheet', prominence: 'signature', note: 'A pale sheet over the clothesline and a light behind it. Within ten minutes it has moths, a lacewing, and one beetle that will not leave.' },
  ],
  radio: {
    stations: [
      { id: 'khol_887', dial: 88.7, band: 'fm', name: 'KHOL — Night Service', character: 'lofi', reception: 0.82, note: 'Tape-saturated instrumentals with the hiss left in. The host says almost nothing and never gives the time.' },
      { id: 'forest_net', dial: 91.3, band: 'fm', name: 'Forest Net Repeater', character: 'environmental', reception: 0.64, note: 'Fire weather, road status, a long silence, then the same three items again.' },
      { id: 'wcrk_1490', dial: 1490, band: 'am', name: 'WCRK 1490', character: 'community', reception: 0.4, note: 'A swap-and-shop for a town that is definitely nearby. Someone is still selling a canoe.' },
      { id: 'gap_signal', dial: 104.1, band: 'fm', name: 'Unlabelled carrier', character: 'strange', reception: 0.22, note: 'A carrier tone with a slow tick under it. It gets clearer when the fire is high, which is almost certainly coincidence.' },
    ],
    baseReception: 0.7,
    receptionNote: 'The ridge blocks the west. Everything comes in from the gap where the creek leaves the bowl.',
    betweenStations: 'Soft pink hiss with a faint 60-cycle hum, and the occasional ghost of a station three counties over.',
  },
  secrets: [
    {
      id: 'ph_carved_initials',
      title: 'The initials on the table',
      discovery: 'Crouch under the picnic table with the flashlight and the underside is covered in decades of carved initials.',
      telling:
        'The same two sets of initials appear in four different years, always together, and then once more alone, much later, in a shakier hand.',
      channels: ['notes', 'campsite-changes'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.5,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ph_lantern_on_the_road',
      title: 'The lantern on the loop road',
      discovery: 'Some nights, a single warm light moves slowly along the loop road above the site and does not stop.',
      telling:
        'It is going the wrong way for a car and too steadily for a person. It passes and the crickets pick up again immediately, which is somehow the reassuring part.',
      channels: ['recurring-figures', 'distant-sounds'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.18,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ph_creek_tin',
      title: 'The tin in the creek',
      discovery: 'A dented tin wedged under the wobbling stepping stone, visible only when the creek is low.',
      telling:
        'Inside: a photograph of this exact site with a different fire ring, a bus ticket, and a note that reads "if you find this, put it back."',
      channels: ['strange-objects', 'notes'],
      oneTime: true,
      leavesEvidence:
        'Once opened, the tin sits closed on the picnic table on every later visit, and the stone stops wobbling.',
      rarity: 0.3,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'ph_squirrel_hoard',
      title: 'The hoard in the snag',
      discovery: 'Follow the squirrel long enough and it goes into a split in the leaning snag.',
      telling:
        'Cones, a bottle cap, a foil marshmallow-bag corner, and — if you have camped here before — a small object you know you left out one previous night.',
      channels: ['wildlife-behaviour', 'campsite-changes'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.35,
      optional: true,
      gatesNothing: true,
    },
  ],
  machine: {
    quirkWeights: { 'sticky-door': 3, 'slow-amber': 2, 'proud-badge': 2, 'double-relay': 1.5 },
    flavourNote:
      'The hollow unit sits level on a poured concrete pad that is older than the machine. Damp gets into the door gasket, so the first close of the night rarely takes.',
    stickerHint: 'CAMPGROUND INSPECTION 08, half peeled, with a newer one stuck over the corner.',
    frostNote: 'Frost comes on grey-blue and fades fast in the damp air — the panel is dry again within a minute of the door opening.',
  },
  procedural: {
    seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'traces', 'machine'],
    variations: [
      { id: 'creek_level', label: 'Creek level', range: { min: 0.35, max: 1 }, unit: 'normalised depth', note: 'Low creek exposes the tin and quiets the ambience; high creek raises the water bed and hides the stones.' },
      { id: 'firewood_stack', label: 'Firewood remaining on the stack', range: { min: 3, max: 14 }, unit: 'rounds', note: 'Never zero. Fuel is not a pressure (§4.1).' },
      { id: 'undergrowth_density', label: 'Bracken density', range: { min: 0.7, max: 1.3 }, unit: 'multiplier', note: 'Seasonal-feeling variation in the low scatter.' },
      { id: 'neighbour_presence', label: 'Neighbouring site occupied', range: { min: 0, max: 1 }, unit: 'probability', note: 'Drives whether distant laughter and a far-off second firelight exist tonight.' },
      { id: 'duff_wetness', label: 'Duff wetness', range: { min: 0.1, max: 0.6 }, unit: 'normalised', note: 'Changes footstep sound and the moisture of gathered kindling.' },
    ],
    invariants: [
      'Site post 11 and its violet laminated card.',
      'The bear box, its dent, and the worn latch.',
      'The leaning snag at fifteen degrees.',
      'Three stepping stones, middle one loose until the tin is found.',
    ],
  },
  discovery: {
    weight: 12,
    affinities: { highland: 1.6, 'maritime-west': 1.3, boreal: 1.1, 'continental-interior': 1, 'arid-interior': 0.7, 'humid-subtropical': 0.7, mediterranean: 0.9, 'maritime-east': 1.1, unknown: 1.5 },
    note: 'The heaviest weight in the catalogue and the default first campsite — the safest possible introduction to the ritual.',
  },
  performance: {
    cost: 'moderate',
    midTierDrawCalls: 74,
    midTierTriangles: 34000,
    dynamicLights: 3,
    lowTierCuts: [
      'Bracken and huckleberry scatter (kit_bracken) drops to 40%.',
      'Young fir infill halves; the fog does the hiding instead.',
      'Creek surface loses its normal map and animates by UV scroll only.',
      'Draw distance 48m → 30m with fog density raised to compensate.',
    ],
    note: 'Trunk count is the cost driver. Instanced lodgepole with two LODs keeps this comfortably inside budget.',
  },
};
