import type { EnvironmentManifest } from '../schema.js';

/**
 * Sweetgrass Coulee — grassland, a slow brown river, and weather you can watch
 * arrive for twenty minutes before it gets to you.
 *
 * The horizon environment. Nothing is close except the fire, which makes the
 * fire enormous.
 */
export const SWEETGRASS_COULEE: EnvironmentManifest = {
  id: 'sweetgrass_coulee',
  name: 'Sweetgrass Coulee',
  tagline: 'Grass to the edge of the world in every direction, and a river going nowhere in particular.',
  inspiration:
    'A cottonwood bend on a prairie river where the grassland breaks into coulees — a barbed-wire fence line, a windmill that no longer pumps, and heat lightning on a horizon eighty kilometres away.',
  biomeTags: ['shortgrass-prairie', 'riparian-cottonwood', 'coulee', 'big-sky'],
  character: {
    temperature: 'warm',
    moisture: 'dry',
    altitude: 'lowland',
    treeCover: 'open',
    water: 'river',
    eeriness: 2,
  },
  arrival: {
    approach:
      'You walk in along a fence line because it is the only thing to follow. Grass to the knee, seed heads catching on everything, and the ground dropping away by degrees until you are suddenly below the level of the prairie.',
    firstHeard:
      'Wind in grass — an enormous, continuous, directionless hush, with the occasional single strand of barbed wire humming a note in it.',
    firstSeen:
      'The windmill, in silhouette, turning slowly for no reason and connected to nothing.',
    underfoot:
      'Dry grass thatch that crackles, then cracked river clay in plates that tip under your weight.',
    arrivalBeat:
      'The coulee bends and there is the cottonwood — one tree the size of a building — with the fire under it and the river going past just beyond, flat and brown and silent.',
    walkSeconds: { min: 30, max: 48 },
  },
  scene: {
    ground: 'grass-thatch',
    groundNote:
      'Fine dry grass over cracked clay, worn to bare dirt under the cottonwood. Firelight travels a long way across it and picks out every seed head.',
    vegetation: [
      { kitId: 'kit_cottonwood', label: 'Plains cottonwood', density: 0.6, heightRange: { min: 14, max: 26 }, lowTierDrop: false, note: 'Three of them along the bend. Enormous, deeply furrowed, and the leaves make a sound like rain in any wind at all.' },
      { kitId: 'kit_shortgrass', label: 'Shortgrass and sage', density: 140, heightRange: { min: 0.15, max: 0.6 }, lowTierDrop: true, note: 'The single densest scatter in the catalogue. It has to move as one surface or the whole place dies.' },
      { kitId: 'kit_willow_bar', label: 'Willow on the gravel bar', density: 20, heightRange: { min: 1, max: 3 }, lowTierDrop: true, note: 'A grey-green fringe along the water, dense enough to hide the beaver and thin enough to see the river through.' },
    ],
    landmarks: [
      { id: 'the_cottonwood', label: 'The big cottonwood', kind: 'natural', handcrafted: true, note: 'One tree, three metres through, with a limb reaching out over the fire ring. Everything at this site is arranged around it.' },
      { id: 'windmill', label: 'The windmill', kind: 'abandoned', handcrafted: true, note: 'A galvanised farm windmill up on the prairie, blades bent, still turning. Silhouetted against every sunset and every lightning flash.' },
      { id: 'fence_line', label: 'The fence line', kind: 'built', handcrafted: true, note: 'Four strands, cedar posts, running dead straight to the horizon in both directions. It hums.' },
      { id: 'gravel_bar', label: 'The gravel bar', kind: 'water', handcrafted: false, note: 'A crescent of rounded stones inside the bend. Warm underfoot until midnight and full of skipping stones.' },
      { id: 'buffalo_rub', label: 'The rubbing stone', kind: 'natural', handcrafted: true, note: 'A granite erratic sitting alone in the grass, polished smooth on one side by a hundred years of animals leaning on it.' },
    ],
    elevation: 'rolling',
    elevationNote:
      'The coulee is a fold twelve metres below the prairie. Down here you are sheltered and invisible; ten steps up the bank you can see for forty kilometres.',
    water: {
      kind: 'river',
      label: 'The river',
      widthM: 40,
      flow: 'slow',
      clarity: 0.15,
      fishable: true,
      skippable: true,
      note: 'Silt brown, moving faster than it looks, and almost completely silent. Catfish and one very large thing that rolls at the surface after midnight.',
    },
    drawDistanceM: 220,
    fog: { colour: '#20201a', density: 0.005, note: 'Dust haze rather than water. Turns the last of the light orange and sits low over the river at dawn.' },
    nightPalette: {
      zenith: '#070911',
      horizon: '#241d17',
      ground: '#3b3220',
      foliage: '#28301d',
      rock: '#4a463c',
      water: '#1c1a16',
      fireGlow: '#ffa04a',
      moonlight: '#c0bda8',
      shadow: '#0a0906',
    },
    skyOpenness: 0.9,
    walkableRadiusM: 58,
  },
  weather: {
    id: 'sweetgrass-coulee',
    weights: { clear: 6, 'high-cloud': 4, wind: 5, overcast: 2, storm: 2, 'light-rain': 1, rain: 1 },
    baseTempC: 19,
    baseWind: 3.4,
    exposure: 0.45,
    skyEventChance: 0.28,
    skyEvents: ['heat-lightning', 'meteor-shower'],
    transitionSeconds: 190,
  },
  weatherCharacter: {
    temperatureNote:
      'Warm and dry, holding heat well past midnight, with a cool river-smelling layer about knee height that you only notice sitting down.',
    windNote:
      'Constant on the prairie and almost nothing in the coulee. You can hear the wind the whole night without ever feeling it, which is the strangest and best thing about this site.',
    exposureNote: 'The coulee walls shelter the pit almost completely. This is the easiest fire in the catalogue.',
    nightRangeC: { min: 12, max: 26 },
  },
  fuel: {
    sources: [
      { woodId: 'aspen', weight: 5, foundAs: 'Cottonwood deadfall, light as paper and everywhere along the bank.', moistureBias: -0.04 },
      { woodId: 'driftwood', weight: 4, foundAs: 'Stranded on the gravel bar by a high water that happened months ago.', moistureBias: -0.02 },
      { woodId: 'oak', weight: 2, foundAs: 'Two cedar fence posts, replaced and stacked, that are technically not oak but burn like it.', moistureBias: -0.1 },
      { woodId: 'birch', weight: 1, foundAs: 'A single piece somebody brought from somewhere else and did not burn.', moistureBias: 0.05 },
    ],
    note:
      'Cottonwood is fast, bright and gone — a beautiful flame and a useless ember. The river driftwood is the good stuff, sun-bleached and dry all the way through, and the two fence posts will hold a bed until dawn if you can bring yourself to burn them.',
  },
  wildlife: [
    {
      id: 'beaver',
      label: 'Beaver',
      shyness: 0.55,
      curiosity: 0.35,
      window: ['dusk', 'early-night', 'deep-night'],
      attractedBy: ['quiet', 'water-edge', 'stillness'],
      repelledBy: ['splashing', 'flashlight', 'voices'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a fresh cut willow stem with pale chisel marks', 'a mud slide down the bank', 'a wake crossing the current at an angle'],
      note: 'Works the willow bar every night. Slaps its tail exactly once if you are careless and then the river is empty for twenty minutes.',
    },
    {
      id: 'nighthawk',
      label: 'Common nighthawk',
      shyness: 0.3,
      curiosity: 0.5,
      window: ['dusk', 'early-night'],
      attractedBy: ['firelight', 'open-sky'],
      repelledBy: ['rain'],
      canPersist: false,
      investigatesObjects: false,
      traces: ['none'],
      note: 'Cuts through the firelight after the moths, high up, with a nasal peent. Occasionally dives and makes a booming sound with its wings that startles everybody, every time.',
    },
    {
      id: 'coyote',
      label: 'Coyote',
      shyness: 0.75,
      curiosity: 0.7,
      window: ['deep-night', 'pre-dawn'],
      attractedBy: ['food-smell', 'quiet', 'moonlight'],
      repelledBy: ['firelight', 'voices', 'camera-flash'],
      canPersist: true,
      investigatesObjects: true,
      traces: ['prints along the gravel bar in a straight purposeful line', 'a marshmallow bag opened very neatly'],
      note: 'Stays out past the firelight and lets you know it is there by choosing to. Never approaches, never threatens; a pair of eyes at forty metres and a chorus at three in the morning.',
    },
    {
      id: 'pelican',
      label: 'White pelicans',
      shyness: 0.6,
      curiosity: 0.1,
      window: ['dawn', 'dusk'],
      attractedBy: ['quiet', 'water-edge'],
      repelledBy: ['footsteps'],
      canPersist: false,
      investigatesObjects: false,
      traces: ['a single enormous feather on the gravel bar'],
      note: 'Nine of them go over at head height in a line at dawn, silent, and the size of them at that range is genuinely startling.',
    },
    {
      id: 'catfish',
      label: 'Something in the river',
      shyness: 0.9,
      curiosity: 0.3,
      window: ['deep-night'],
      attractedBy: ['stillness', 'crumbs'],
      repelledBy: ['splashing'],
      canPersist: true,
      investigatesObjects: false,
      traces: ['a slow ring on the surface, out past the bar, already fading by the time you look'],
      note: 'It rolls once a night. It is bigger than it should be. It is never caught, and the fishing here is deliberately not about catching it.',
    },
  ],
  ambience: {
    wind: { character: 'steady', baseLevel: 0.48, gustiness: 0.4, material: 'a hundred metres of grass, and one strand of barbed wire' },
    insectDensity: 0.82,
    insectNote: 'Enormous. Layered cricket and katydid chorus with distinct near and far fields, and a single mosquito that finds the microphone about once a minute.',
    waterPresence: 0.18,
    reverb: 'clearing',
    reverbNote: 'Almost none. The grass eats every reflection, so voices sound close and small and the silence between them is total.',
    distantEvents: [
      { id: 'far_thunder', label: 'Thunder from a storm that never arrives', weight: 5, minGapSeconds: 150, note: 'Twelve seconds after the flash, and the flash is on a horizon you can barely see.' },
      { id: 'freight_train', label: 'A freight train', weight: 4, minGapSeconds: 480, note: 'Four minutes of it, from the far side of the prairie. Two horn notes at a crossing you will never find.' },
      { id: 'windmill_squeal', label: 'The windmill turns over', weight: 5, minGapSeconds: 70, note: 'A dry metal complaint, one revolution, then it stops again.' },
      { id: 'cattle_far', label: 'Cattle, somewhere', weight: 3, minGapSeconds: 300, note: 'One cow, a long way off, unhappy about something.' },
      { id: 'fence_hum', label: 'The fence line hums', weight: 4, minGapSeconds: 110, note: 'A single sustained note off the top wire when the wind hits the right speed.' },
    ],
    nightFloorDb: -46,
  },
  activities: [
    { id: 'fire-tending', label: 'Tend the fire', prominence: 'available', note: 'Forgiving and sheltered. The site where a new player can just enjoy a fire.' },
    { id: 'fishing', label: 'Fish the river', prominence: 'notable', note: 'A rod propped on a forked stick with a bell on the tip. Mostly it is about the bell not ringing.' },
    { id: 'stone-skipping', label: 'Skip stones', prominence: 'notable', note: 'The gravel bar is full of perfect ones and the river is slow. Double-digit skips are achievable.' },
    { id: 'stargazing', label: 'Stargaze', prominence: 'notable', note: 'Ninety percent sky. Lie on the warm gravel bar and the horizon disappears entirely.' },
    { id: 'binoculars', label: 'Binoculars', prominence: 'available', note: 'For the storm on the horizon, and for whatever the windmill is silhouetted against tonight.' },
    { id: 'photography', label: 'Photograph', prominence: 'notable', note: 'Heat lightning behind the windmill is the shot this environment exists to produce.' },
    { id: 'radio', label: 'Radio', prominence: 'signature', note: 'The best radio site in the catalogue after dark. Flat ground, no terrain, and a hundred AM stations skipping in off the ionosphere.' },
    { id: 'flashlight', label: 'Flashlight', prominence: 'available', note: 'Sweep the grass and a dozen small green eyes look back. Wolf spiders. Entirely harmless and completely delightful.' },
    { id: 'wildlife-watching', label: 'Watch for wildlife', prominence: 'available', note: 'The beaver is on a schedule; the coyote is not.' },
    { id: 'grass-whistle', label: 'Grass whistle', prominence: 'signature', note: 'A broad blade held between the thumbs. It takes several tries to get a note, and once you can, you can do it every time, forever.' },
  ],
  radio: {
    stations: [
      { id: 'kcou_1055', dial: 105.5, band: 'fm', name: 'KCOU — All Night Country', character: 'lofi', reception: 0.78, note: 'Steel guitar and long silences between records. The DJ reads the temperature in a town of four hundred people every half hour.' },
      { id: 'skip_1120', dial: 1120, band: 'am', name: 'Skip — 1120 kHz', character: 'community', reception: 0.62, note: 'Different station every hour as the ionosphere moves. Sports, then preaching, then a phone-in about a dog.' },
      { id: 'ag_weather', dial: 1610, band: 'am', name: 'Agricultural weather', character: 'weather-service', reception: 0.7, note: 'Soil temperatures, dew point, spray conditions, and a hail warning for a county with an unpronounceable name.' },
      { id: 'time_signal', dial: 5000, band: 'shortwave', name: 'Time signal', character: 'environmental', reception: 0.68, note: 'A tick every second, a tone every minute, and a voice reading Coordinated Universal Time forever. Falling asleep to it is a real thing people will do.' },
      { id: 'grain_elevator', dial: 92.9, band: 'fm', name: 'Unmodulated carrier', character: 'strange', reception: 0.3, note: 'Dead air with a heartbeat under it, exactly 42 beats a minute. It is almost certainly a grain-dryer motor inducting into a transmitter. Almost.' },
    ],
    baseReception: 0.75,
    receptionNote: 'No terrain in any direction. Everything gets in, including things that should not be able to.',
    betweenStations: 'Wide flat static with slow ionospheric swells in it, and every so often two stations occupying the same frequency at once.',
  },
  secrets: [
    {
      id: 'sg_windmill_plate',
      title: 'The windmill plate',
      discovery: 'Climb the ladder far enough and there is a maker’s plate bolted to the tower.',
      telling:
        'A company, a town, a patent year — and scratched underneath with a nail, a list of five names and a sixth added much later in a different hand, with no date.',
      channels: ['notes', 'strange-objects'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.4,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'sg_the_rub_stone',
      title: 'What is under the rubbing stone',
      discovery: 'The erratic sits on a low mound. There is a gap under the polished side big enough for a hand.',
      telling:
        'A tobacco tin, packed with a child’s drawings of this exact bend — the tree, the windmill, the river — signed with a first name and a series of ages: 7, 8, 9, 11.',
      channels: ['strange-objects', 'notes'],
      oneTime: true,
      leavesEvidence: 'The tin stays on the flat top of the stone afterward, weighted down with a river cobble, and new drawings never appear.',
      rarity: 0.22,
      optional: true,
      gatesNothing: true,
    },
    {
      id: 'sg_storm_that_misses',
      title: 'The storm that goes around',
      discovery: 'A full supercell builds on the horizon over about forty minutes, lit from the inside, and passes north without a single drop reaching the coulee.',
      telling:
        'You watch an entire weather system be enormous somewhere else. The grass goes flat, the fence hums a fourth higher, and then it is quiet and the crickets restart.',
      channels: ['campsite-changes', 'distant-sounds'],
      oneTime: false,
      leavesEvidence: null,
      rarity: 0.16,
      optional: true,
      gatesNothing: true,
    },
  ],
  machine: {
    quirkWeights: { 'proud-badge': 3, 'double-relay': 2.5, 'long-hold': 2, 'flicker-segment': 1.5 },
    flavourNote:
      'Dust has got into everything on this unit — the vents, the dial detents, the gap under the badge. It runs perfectly and it will never look clean again, and there is a hand-drawn tally of runs on the inside of the service panel that somebody has been keeping up for years.',
    stickerHint: 'LOT 14, and beneath it a county fair sticker from a year that ends in 99.',
    frostNote: 'The frost picks up the dust as it forms, so the window frosts a very faint gold instead of white.',
  },
  procedural: {
    seedStreams: ['scatter', 'weather', 'wildlife', 'radio', 'river', 'sky', 'machine'],
    variations: [
      { id: 'river_level', label: 'River level', range: { min: 0.3, max: 0.95 }, unit: 'normalised', note: 'Governs the size of the gravel bar, which governs skipping stones, the pelican landing and where the coyote walks.' },
      { id: 'grass_height', label: 'Grass height', range: { min: 0.6, max: 1.4 }, unit: 'multiplier', note: 'Seasonal feel, and how much of the walk in is above your knees.' },
      { id: 'storm_distance', label: 'Distance to tonight’s storm', range: { min: 20, max: 140 }, unit: 'kilometres', note: 'It never arrives. It is only ever a light show and a sound.' },
      { id: 'windmill_rate', label: 'Windmill revolutions', range: { min: 0, max: 22 }, unit: 'per minute', note: 'Tied to wind. At zero it just stands there, which is worse.' },
      { id: 'am_skip', label: 'Ionospheric skip quality', range: { min: 0.2, max: 1 }, unit: 'normalised', note: 'How far the AM band reaches tonight, and therefore who you get to listen to.' },
    ],
    invariants: [
      'The big cottonwood and the limb over the fire ring.',
      'The windmill and its bent blade.',
      'The fence line running to both horizons.',
      'The rubbing stone, polished on the south side.',
    ],
  },
  discovery: {
    weight: 10,
    affinities: { 'continental-interior': 2.3, 'arid-interior': 1.4, mediterranean: 1.1, unknown: 1.2, boreal: 0.9, highland: 0.9, 'humid-subtropical': 1, 'maritime-west': 0.7, 'maritime-east': 0.7 },
    note: 'The easy, expansive one. Weighted inland, freely available everywhere; a good second environment for almost any player.',
  },
  performance: {
    cost: 'moderate',
    midTierDrawCalls: 58,
    midTierTriangles: 42000,
    dynamicLights: 3,
    lowTierCuts: [
      'Grass scatter 140 → 40 per 100m² with a grass-coloured ground texture doing the rest of the work.',
      'Per-blade wind animation becomes a whole-patch UV shear.',
      'River surface loses reflections and keeps only the scroll and the dither.',
      'Draw distance 220m → 120m; the windmill and the storm move to billboards.',
    ],
    note: 'Grass instancing is the only real cost and it is a well-understood one. The cottonwoods are three high-detail hero meshes and everything else is nearly free.',
  },
};
