/**
 * Packs every sprite module into one atlas and one manifest.
 *
 * A single image and a table of rectangles, which is how this was done on the
 * hardware being imitated and is still the right answer: one request, one
 * texture, no layout thrash from a hundred `<img>` elements appearing at
 * different moments.
 *
 * Deterministic on purpose. Sprites are sorted by name and packed into a fixed
 * grid, so regenerating without changing a drawing produces a byte-identical
 * PNG — which means the atlas can be committed and reviewed like source, and a
 * diff in it means somebody changed a drawing.
 *
 *   node tools/sprites/build.mjs
 */

import { mkdirSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { Pix, encodePng } from './canvas.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');

/** Every cell is this size. One size keeps the packing trivial and the HUD calm. */
const CELL = 32;
/** Cells per row in the atlas. */
const COLUMNS = 8;

/**
 * The eight tiles that make the HUD's frame, laid out the way CSS wants them.
 *
 * `border-image` is the one part of CSS that does nine-slicing properly — it
 * repeats the edges, holds the corners at a fixed size, and rescales the whole
 * thing for free when the window changes. But it wants the nine pieces
 * arranged as one contiguous 3x3 image, and the atlas necessarily has them
 * scattered in name order among the icons. So the frame is emitted a second
 * time as its own small sheet: 96x96, the tiles in reading order, the middle
 * left transparent because that is where the game is.
 *
 * The duplication is about a kilobyte and buys a frame that costs one CSS
 * property instead of eight absolutely positioned elements that have to be
 * kept in agreement about their own thickness.
 */
const FRAME_TILES = [
  ['bezel-tl', 'bezel-top', 'bezel-tr'],
  ['bezel-left', null, 'bezel-right'],
  ['bezel-bl', 'bezel-bottom', 'bezel-br'],
];
/** Where the frame's own artwork stops and the world starts, in pixels. */
const FRAME_SLICE = 13;

async function loadSprites() {
  const dir = join(HERE, 'icons');
  const files = readdirSync(dir)
    // `_`-prefixed files are references and scratch, not sprites.
    .filter((name) => name.endsWith('.mjs') && !name.startsWith('_'))
    .sort();
  const sprites = [];
  for (const file of files) {
    const module = await import(pathToFileURL(join(dir, file)).href);
    const family = file.replace(/\.mjs$/, '');
    const exported = module.SPRITES;
    if (!Array.isArray(exported)) {
      throw new Error(`${file} must export a SPRITES array`);
    }
    for (const sprite of exported) {
      if (!sprite.name || typeof sprite.draw !== 'function') {
        throw new Error(`${file}: every sprite needs a name and a draw(pix)`);
      }
      sprites.push({ ...sprite, family });
    }
  }
  // Sorted, so the atlas layout does not depend on filesystem order.
  sprites.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  const seen = new Set();
  for (const sprite of sprites) {
    if (seen.has(sprite.name)) throw new Error(`duplicate sprite name: ${sprite.name}`);
    seen.add(sprite.name);
  }
  return sprites;
}

function main(sprites) {
  const rows = Math.max(1, Math.ceil(sprites.length / COLUMNS));
  const atlas = new Pix(COLUMNS * CELL, rows * CELL);
  const frames = {};

  sprites.forEach((sprite, index) => {
    const cell = new Pix(CELL, CELL);
    sprite.draw(cell);
    const column = index % COLUMNS;
    const row = Math.floor(index / COLUMNS);
    atlas.stamp(cell, column * CELL, row * CELL);
    frames[sprite.name] = { x: column * CELL, y: row * CELL, family: sprite.family };
  });

  mkdirSync(join(ROOT, 'apps/web/public/sprites'), { recursive: true });
  writeFileSync(join(ROOT, 'apps/web/public/sprites/atlas.png'), encodePng(atlas));

  // The frame, again, as a nine-slice. Skipped rather than faked if the bezel
  // family is absent, so the build still works with only some families drawn.
  const byName = new Map(sprites.map((sprite) => [sprite.name, sprite]));
  const haveFrame = FRAME_TILES.flat().every((name) => name === null || byName.has(name));
  if (haveFrame) {
    const frame = new Pix(CELL * 3, CELL * 3);
    FRAME_TILES.forEach((row, y) => {
      row.forEach((name, x) => {
        if (name === null) return;
        const cell = new Pix(CELL, CELL);
        byName.get(name).draw(cell);
        frame.stamp(cell, x * CELL, y * CELL);
      });
    });
    writeFileSync(join(ROOT, 'apps/web/public/sprites/frame.png'), encodePng(frame));
  }

  const names = Object.keys(frames).sort();
  const manifest = `/**
 * Generated by \`node tools/sprites/build.mjs\`. Do not edit by hand.
 *
 * The drawings live in \`tools/sprites/icons/\`; this is only where they landed
 * in the atlas. Regenerating without changing a drawing produces the same file.
 */

export const SPRITE_CELL = ${CELL};
export const SPRITE_SHEET = 'sprites/atlas.png';
export const SPRITE_SHEET_SIZE = { width: ${atlas.width}, height: ${atlas.height} } as const;

/** The same bezel again as a contiguous 3x3, for CSS \`border-image\`. */
export const SPRITE_FRAME = ${haveFrame ? "'sprites/frame.png'" : 'null'};
export const SPRITE_FRAME_SLICE = ${FRAME_SLICE};

export type SpriteName =
${names.length === 0 ? '  never' : names.map((name) => `  | '${name}'`).join('\n')};

export const SPRITES: Record<SpriteName, { readonly x: number; readonly y: number }> = {
${names.map((name) => `  '${name}': { x: ${frames[name].x}, y: ${frames[name].y} },`).join('\n')}
};
`;
  mkdirSync(join(ROOT, 'apps/web/src/ui/sprites'), { recursive: true });
  writeFileSync(join(ROOT, 'apps/web/src/ui/sprites/atlas.ts'), manifest);

  return { count: sprites.length, width: atlas.width, height: atlas.height };
}

const sprites = await loadSprites();
const result = main(sprites);
// eslint-disable-next-line no-console
console.log(`packed ${result.count} sprites into ${result.width}x${result.height}`);
