/**
 * Generated by `node tools/sprites/build.mjs`. Do not edit by hand.
 *
 * The drawings live in `tools/sprites/icons/`; this is only where they landed
 * in the atlas. Regenerating without changing a drawing produces the same file.
 */

export const SPRITE_CELL = 32;
export const SPRITE_SHEET = 'sprites/atlas.png';
export const SPRITE_SHEET_SIZE = { width: 256, height: 128 } as const;

export type SpriteName =
  | 'obj-binoculars'
  | 'obj-camera'
  | 'obj-chocolate'
  | 'obj-graham'
  | 'obj-kindling'
  | 'obj-log'
  | 'obj-machine'
  | 'obj-marshmallow'
  | 'obj-plate'
  | 'obj-radio'
  | 'obj-rod'
  | 'obj-sandwich'
  | 'obj-seat'
  | 'obj-stone'
  | 'obj-tinder'
  | 'obj-torch'
  | 'verb-add-log'
  | 'verb-bank'
  | 'verb-blow'
  | 'verb-leave-out'
  | 'verb-look'
  | 'verb-photo'
  | 'verb-poke'
  | 'verb-rake'
  | 'verb-sit'
  | 'verb-stand'
  | 'verb-strike'
  | 'verb-take';

export const SPRITES: Record<SpriteName, { readonly x: number; readonly y: number }> = {
  'obj-binoculars': { x: 0, y: 0 },
  'obj-camera': { x: 32, y: 0 },
  'obj-chocolate': { x: 64, y: 0 },
  'obj-graham': { x: 96, y: 0 },
  'obj-kindling': { x: 128, y: 0 },
  'obj-log': { x: 160, y: 0 },
  'obj-machine': { x: 192, y: 0 },
  'obj-marshmallow': { x: 224, y: 0 },
  'obj-plate': { x: 0, y: 32 },
  'obj-radio': { x: 32, y: 32 },
  'obj-rod': { x: 64, y: 32 },
  'obj-sandwich': { x: 96, y: 32 },
  'obj-seat': { x: 128, y: 32 },
  'obj-stone': { x: 160, y: 32 },
  'obj-tinder': { x: 192, y: 32 },
  'obj-torch': { x: 224, y: 32 },
  'verb-add-log': { x: 0, y: 64 },
  'verb-bank': { x: 32, y: 64 },
  'verb-blow': { x: 64, y: 64 },
  'verb-leave-out': { x: 96, y: 64 },
  'verb-look': { x: 128, y: 64 },
  'verb-photo': { x: 160, y: 64 },
  'verb-poke': { x: 192, y: 64 },
  'verb-rake': { x: 224, y: 64 },
  'verb-sit': { x: 0, y: 96 },
  'verb-stand': { x: 32, y: 96 },
  'verb-strike': { x: 64, y: 96 },
  'verb-take': { x: 96, y: 96 },
};
